-- This query extracts the number of crates checked-in per crop type in a particular day/year

SELECT
    acm.checkin_farmer as farmer_id,
    acm.cooling_unit_id as cooling_unit_id,
    -- Conditional aggregation for each crop
    SUM(CASE WHEN acm.crop_name = 'African star apple' THEN 1 ELSE 0 END) AS "African star apple(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'African star apple' THEN acm.weight ELSE 0 END) AS "African star apple(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Apple' THEN 1 ELSE 0 END) AS "Apple(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Apple' THEN acm.weight ELSE 0 END) AS "Apple(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Avocado' THEN 1 ELSE 0 END) AS "Avocado(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Avocado' THEN acm.weight ELSE 0 END) AS "Avocado(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Banana' THEN 1 ELSE 0 END) AS "Banana(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Banana' THEN acm.weight ELSE 0 END) AS "Banana(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Bathua (Chenopodium)' THEN 1 ELSE 0 END) AS "Bathua (Chenopodium)(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Bathua (Chenopodium)' THEN acm.weight ELSE 0 END) AS "Bathua (Chenopodium)(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Beans' THEN 1 ELSE 0 END) AS "Beans(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Beans' THEN acm.weight ELSE 0 END) AS "Beans(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Beetroot' THEN 1 ELSE 0 END) AS "Beetroot(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Beetroot' THEN acm.weight ELSE 0 END) AS "Beetroot(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Bitter Gourd' THEN 1 ELSE 0 END) AS "Bitter Gourd(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Bitter Gourd' THEN acm.weight ELSE 0 END) AS "Bitter Gourd(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Bitter Leaf' THEN 1 ELSE 0 END) AS "Bitter Leaf(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Bitter Leaf' THEN acm.weight ELSE 0 END) AS "Bitter Leaf(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Bottle Gourd' THEN 1 ELSE 0 END) AS "Bottle Gourd(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Bottle Gourd' THEN acm.weight ELSE 0 END) AS "Bottle Gourd(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Brinjal (Aubergine)' THEN 1 ELSE 0 END) AS "Brinjal (Aubergine)(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Brinjal (Aubergine)' THEN acm.weight ELSE 0 END) AS "Brinjal (Aubergine)(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Broccoli' THEN 1 ELSE 0 END) AS "Broccoli(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Broccoli' THEN acm.weight ELSE 0 END) AS "Broccoli(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Cabbage' THEN 1 ELSE 0 END) AS "Cabbage(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Cabbage' THEN acm.weight ELSE 0 END) AS "Cabbage(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Capsicum (Bell Pepper)' THEN 1 ELSE 0 END) AS "Capsicum (Bell Pepper)(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Capsicum (Bell Pepper)' THEN acm.weight ELSE 0 END) AS "Capsicum (Bell Pepper)(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Carrot' THEN 1 ELSE 0 END) AS "Carrot(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Carrot' THEN acm.weight ELSE 0 END) AS "Carrot(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Cauliflower' THEN 1 ELSE 0 END) AS "Cauliflower(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Cauliflower' THEN acm.weight ELSE 0 END) AS "Cauliflower(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Colacasia' THEN 1 ELSE 0 END) AS "Colacasia(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Colacasia' THEN acm.weight ELSE 0 END) AS "Colacasia(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Coriander' THEN 1 ELSE 0 END) AS "Coriander(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Coriander' THEN acm.weight ELSE 0 END) AS "Coriander(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Cucumber' THEN 1 ELSE 0 END) AS "Cucumber(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Cucumber' THEN acm.weight ELSE 0 END) AS "Cucumber(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Flat Beans' THEN 1 ELSE 0 END) AS "Flat Beans(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Flat Beans' THEN acm.weight ELSE 0 END) AS "Flat Beans(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Fluted pumpkin (leaves)' THEN 1 ELSE 0 END) AS "Fluted pumpkin (leaves)(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Fluted pumpkin (leaves)' THEN acm.weight ELSE 0 END) AS "Fluted pumpkin (leaves)(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Garlic' THEN 1 ELSE 0 END) AS "Garlic(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Garlic' THEN acm.weight ELSE 0 END) AS "Garlic(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Ginger' THEN 1 ELSE 0 END) AS "Ginger(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Ginger' THEN acm.weight ELSE 0 END) AS "Ginger(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Grapes' THEN 1 ELSE 0 END) AS "Grapes(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Grapes' THEN acm.weight ELSE 0 END) AS "Grapes(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Green Chilli' THEN 1 ELSE 0 END) AS "Green Chilli(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Green Chilli' THEN acm.weight ELSE 0 END) AS "Green Chilli(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Green Gram' THEN 1 ELSE 0 END) AS "Green Gram(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Green Gram' THEN acm.weight ELSE 0 END) AS "Green Gram(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Guava' THEN 1 ELSE 0 END) AS "Guava(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Guava' THEN acm.weight ELSE 0 END) AS "Guava(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Ivy Gourd' THEN 1 ELSE 0 END) AS "Ivy Gourd(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Ivy Gourd' THEN acm.weight ELSE 0 END) AS "Ivy Gourd(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Jackfruit' THEN 1 ELSE 0 END) AS "Jackfruit(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Jackfruit' THEN acm.weight ELSE 0 END) AS "Jackfruit(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Jute leaves' THEN 1 ELSE 0 END) AS "Jute leaves(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Jute leaves' THEN acm.weight ELSE 0 END) AS "Jute leaves(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Ladyfinger' THEN 1 ELSE 0 END) AS "Ladyfinger(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Ladyfinger' THEN acm.weight ELSE 0 END) AS "Ladyfinger(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Lemon' THEN 1 ELSE 0 END) AS "Lemon(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Lemon'THEN acm.weight ELSE 0 END) AS "Lemon(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Lettuce' THEN 1 ELSE 0 END) AS "Lettuce(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Lettuce' THEN acm.weight ELSE 0 END) AS "Lettuce(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Litchi' THEN 1 ELSE 0 END) AS "Litchi(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Litchi' THEN acm.weight ELSE 0 END) AS "Litchi(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Mango' THEN 1 ELSE 0 END) AS "Mango(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Mango' THEN acm.weight ELSE 0 END) AS "Mango(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Mint leaves' THEN 1 ELSE 0 END) AS "Mint leaves(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Mint leaves' THEN acm.weight ELSE 0 END) AS "Mint leaves(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Musk Melon' THEN 1 ELSE 0 END) AS "Musk Melon(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Musk Melon' THEN acm.weight ELSE 0 END) AS "Musk Melon(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Onion' THEN 1 ELSE 0 END) AS "Onion(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Onion' THEN acm.weight ELSE 0 END) AS "Onion(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Orange' THEN 1 ELSE 0 END) AS "Orange(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Orange' THEN acm.weight ELSE 0 END) AS "Orange(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Other' THEN 1 ELSE 0 END) AS "Other(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Other' THEN acm.weight ELSE 0 END) AS "Other(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Papaya' THEN 1 ELSE 0 END) AS "Papaya(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Papaya' THEN acm.weight ELSE 0 END) AS "Papaya(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Peach' THEN 1 ELSE 0 END) AS "Peach(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Peach' THEN acm.weight ELSE 0 END) AS "Peach(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Pear' THEN 1 ELSE 0 END) AS "Pear(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Pear' THEN acm.weight ELSE 0 END) AS "Pear(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Peas' THEN 1 ELSE 0 END) AS "Peas(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Peas' THEN acm.weight ELSE 0 END) AS "Peas(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Pineapple' THEN 1 ELSE 0 END) AS "Pineapple(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Pineapple' THEN acm.weight ELSE 0 END) AS "Pineapple(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Pointed Gourd' THEN 1 ELSE 0 END) AS "Pointed Gourd(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Pointed Gourd' THEN acm.weight ELSE 0 END) AS "Pointed Gourd(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Pomegranate' THEN 1 ELSE 0 END) AS "Pomegranate(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Pomegranate' THEN acm.weight ELSE 0 END) AS "Pomegranate(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Potato' THEN 1 ELSE 0 END) AS "Potato(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Potato' THEN acm.weight ELSE 0 END) AS "Potato(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Pumpkin' THEN 1 ELSE 0 END) AS "Pumpkin(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Pumpkin' THEN acm.weight ELSE 0 END) AS "Pumpkin(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Radish' THEN 1 ELSE 0 END) AS "Radish(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Radish' THEN acm.weight ELSE 0 END) AS "Radish(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Raw Banana' THEN 1 ELSE 0 END) AS "Raw Banana(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Raw Banana' THEN acm.weight ELSE 0 END) AS "Raw Banana(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Scent leaf' THEN 1 ELSE 0 END) AS "Scent leaf(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Scent leaf' THEN acm.weight ELSE 0 END) AS "Scent leaf(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Spinach' THEN 1 ELSE 0 END) AS "Spinach(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Spinach' THEN acm.weight ELSE 0 END) AS "Spinach(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Spring onion' THEN 1 ELSE 0 END) AS "Spring onion(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Spring onion' THEN acm.weight ELSE 0 END) AS "Spring onion(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Strawberry' THEN 1 ELSE 0 END) AS "Strawberry(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Strawberry' THEN acm.weight ELSE 0 END) AS "Strawberry(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Sweet Lime' THEN 1 ELSE 0 END) AS "Sweet Lime(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Sweet Lime' THEN acm.weight ELSE 0 END) AS "Sweet Lime(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Tapioca (Cassava)' THEN 1 ELSE 0 END) AS "Tapioca (Cassava)(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Tapioca (Cassava)' THEN acm.weight ELSE 0 END) AS "Tapioca (Cassava)(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Taro root' THEN 1 ELSE 0 END) AS "Taro root(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Taro root' THEN acm.weight ELSE 0 END) AS "Taro root(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Tomato' THEN 1 ELSE 0 END) AS "Tomato(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Tomato' THEN acm.weight ELSE 0 END) AS "Tomato(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Waterleaf' THEN 1 ELSE 0 END) AS "Waterleaf(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Waterleaf' THEN acm.weight ELSE 0 END) AS "Waterleaf(Check-in-kg)",
    SUM(CASE WHEN acm.crop_name = 'Water Melon' THEN 1 ELSE 0 END) AS "Water Melon(Check-in)",
    SUM(CASE WHEN acm.crop_name = 'Water Melon' THEN acm.weight ELSE 0 END) AS "Water Melon(Check-in-kg)"

FROM
    analytics_crate_movements acm
WHERE
    acm.checkin_date >= '%(year)s-%(month)s-%(day)s 00:00:00'
    AND acm.checkin_date <= '%(year)s-%(month)s-%(day)s 23:59:59'
    AND acm.checkin_operator IS NOT NULL
GROUP BY
    acm.checkin_farmer, acm.cooling_unit_id;
