export enum ECommonTutorialSteps {
  INITIAL_STEP = 1,
  OPEN_DRAWER_STEP = 2,
  REPEAT_TUTORIAL_STEP = 3,
  GO_TO_MANAGEMENT_STEP = 4,
  COOLING_UNIT_STEP = 9,
  MORE_STEP = 15,
  HISTORY_STEP = 16,
  COOLING_UNITS_STEP = 17,
  FINAL_STEP = 22,
}

export enum EMarketplaceTutorialSteps {
  MARKETPLACE_STEP_1 = 43,
  MARKETPLACE_STEP_2 = 44,
  SHOPPING_CART_STEP = 45,
  MARKETPLACE_STEP_3 = 46,
  MY_ORDERS_STEP = 47,
  LIST_FOR_SALE_STEP = 48,
  COMMON_LIST_FOR_SALE_STEP = 49,
  COMMON_LIST_FOR_SALE_PRICE_STEP = 50,
}

export enum EOperatorTutorialSteps {
  GO_TO_COOLING_USERS_STEP = 5,
  LIST_COOLING_USERS_STEP = 6,
  ADD_COOLING_USER_NAVIGATION_STEP = 7,
  COOLING_USER_MODAL_STEP = 8,
  INITIATE_CHECK_IN_STEP_1 = 10,
  INITIATE_CHECK_IN_STEP_2 = 11,
  CHECK_IN_STEP_1 = 12,
  CHECK_IN_STEP_2 = 13,
  CHECK_IN_STEP_3 = 14,
  ROOM_CONDITIONS_STEP = 18,
  CHECK_OUT_STEP_1 = 19,
  CHECK_OUT_STEP_2 = 20,
  CHECK_OUT_STEP_3 = 21,
}

export enum EEmployeeTutorialSteps {
  LOCATIONS_STEP = 23,
  ADD_LOCATION_STEP = 24,
  COOLING_UNITS_STEP = 25,
  ADD_COOLING_UNIT_STEP = 26,
  ADD_EMPLOYEES_OPERATORS_STEP = 27,
  EMPLOYEE_COOLING_UNITS_STEP = 28,
}

export enum EFarmerTutorialSteps {
  GO_TO_ACCOUNT_DETAILS_STEP = 29,
  GO_TO_LOCALIZATION_PREFERENCES_STEP = 30,
  GO_TO_PERSONAL_DETAILS = 31,
  GO_TO_COOLING_USERS_SURVEY_STEP = 32,
  GO_TO_KNOWLEDGE_HUB_STEP = 33,
  GO_TO_FAQ_STEP = 34,
  DASHBOARD_STEP_1 = 35,
  DASHBOARD_STEP_2 = 36,
  DASHBOARD_STEP_3 = 37,
  DASHBOARD_STEP_4 = 38,
  DASHBOARD_STEP_5 = 39,
  DASHBOARD_STEP_6 = 40,
  COOLING_UNITS_FARMER_STEP = 41,
  MARKET_PRICE = 42,
}
