# Generated by Django 3.2.4 on 2024-10-01 12:55

import base.utils.currencies
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0035_alter_currency_fields'),
        ('user', '0025_alter_currency_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked_at')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
                ('discount_percentage', models.FloatField(default=0, verbose_name='discount_percentage')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketListedCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('delisted_at', models.DateTimeField(blank=True, null=True, verbose_name='delisted_at')),
                ('currency', models.CharField(default='NGN', max_length=3, validators=[base.utils.currencies.validate_currency], verbose_name='currency')),
                ('produce_price_per_kg', models.FloatField(default=0, verbose_name='produce_price_per_kg')),
                ('cmp_last_updated_at', models.DateTimeField(default=timezone.now, verbose_name='cmp_last_updated_at')),
                ('cmp_pending_in_cooling_fees', models.FloatField(default=0, verbose_name='cmp_pending_in_cooling_fees')),
                ('cmp_pending_in_cooling_fees_price_per_kg', models.FloatField(default=0, verbose_name='cmp_pending_in_cooling_fees_price_per_kg')),
                ('cmp_weight_locked_in_payment_pending_orders_in_kg', models.FloatField(default=0, verbose_name='cmp_weight_locked_in_payment_pending_orders_in_kg')),
                ('cmp_available_weight_in_kg', models.FloatField(default=0, verbose_name='cmp_available_weight_in_kg')),
                ('crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listed_crates', to='storage.crate')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cart', 'Cart'), ('abandoned-cart', 'Abandoned Cart'), ('payment-pending', 'Payment Pending'), ('paid', 'Paid')], default='cart', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('currency', models.CharField(default='NGN', max_length=3, validators=[base.utils.currencies.validate_currency], verbose_name='currency')),
                ('paystack_split_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='paystack_split_code')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid_at')),
                ('amount_paid', models.FloatField(default=0, verbose_name='amount_paid')),
                ('cmp_last_updated_at', models.DateTimeField(default=timezone.now, verbose_name='cmp_last_updated_at')),
                ('cmp_total_produce_amount', models.FloatField(default=0, verbose_name='cmp_total_produce_amount')),
                ('cmp_total_cooling_fees_amount', models.FloatField(default=0, verbose_name='cmp_total_cooling_fees_amount')),
                ('cmp_total_coldtivate_amount', models.FloatField(default=0, verbose_name='cmp_total_coldtivate_amount')),
                ('cmp_total_discount_amount', models.FloatField(default=0, verbose_name='cmp_total_discount_amount')),
                ('cmp_total_payment_fees_amount', models.FloatField(default=0, verbose_name='cmp_total_payment_fees_amount')),
                ('cmp_total_amount', models.FloatField(default=0, verbose_name='cmp_total_amount')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaystackAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_default_account', models.BooleanField(default=False, verbose_name='is_default_account')),
                ('account_type', models.SmallIntegerField(choices=[('1', 'Personal'), ('2', 'Business')], verbose_name='account_type')),
                ('bank_code', models.CharField(max_length=9, verbose_name='bank_code')),
                ('country_code', models.CharField(max_length=2, verbose_name='country_code')),
                ('account_number', models.CharField(max_length=30, verbose_name='account_number')),
                ('account_name', models.CharField(max_length=100, verbose_name='account_name')),
                ('paystack_subaccount_code', models.CharField(max_length=20, verbose_name='paystack_subaccount_code')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_accounts', to='user.company')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCrateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_entire_crate', models.BooleanField(default=False, verbose_name='ordered_entire_crate')),
                ('ordered_produce_weight', models.FloatField(default=0, verbose_name='ordered_produce_weight')),
                ('frozen_crate_available_weight', models.FloatField(default=0, verbose_name='frozen_crate_available_weight')),
                ('frozen_produce_price_per_kg', models.FloatField(default=0, verbose_name='frozen_produce_price_per_kg')),
                ('cmp_last_updated_at', models.DateTimeField(default=timezone.now, verbose_name='cmp_last_updated_at')),
                ('cmp_produce_amount', models.FloatField(default=0, verbose_name='cmp_produce_amount')),
                ('cmp_cooling_fees_amount', models.FloatField(default=0, verbose_name='cmp_cooling_fees_amount')),
                ('cmp_discount_amount', models.FloatField(default=0, verbose_name='cmp_discount_amount')),
                ('cmp_total_amount', models.FloatField(default=0, verbose_name='cmp_total_amount')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.coupon')),
                ('market_listed_crate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.marketlistedcrate', verbose_name='order_item_market_listed_crate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order', verbose_name='items')),
                ('post_order_crate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originated_order_item', to='storage.crate', verbose_name='post_order_crate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paystackaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('is_default_account', True)), fields=('created_by_user', 'is_default_account'), name='unique_default_user_account'),
        ),
        migrations.AddConstraint(
            model_name='paystackaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('is_default_account', True)), fields=('company', 'is_default_account'), name='unique_default_company_account'),
        ),
        migrations.AddIndex(
            model_name='ordercrateitem',
            index=models.Index(fields=['order'], name='quicker_order_items_lookup'),
        ),
        migrations.AddIndex(
            model_name='ordercrateitem',
            index=models.Index(fields=['coupon'], name='quicker_coupon_lookup'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by_user', 'status'], name='quicker_user_order_lookup'),
        ),
        migrations.AddConstraint(
            model_name='marketlistedcrate',
            constraint=models.UniqueConstraint(condition=models.Q(('delisted_at__isnull', True)), fields=('crate',), name='unique_active_listing_per_crate'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__gt', 0), ('discount_percentage__lt', 1)), name='valid_discount_percentage'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('created_by_user', 'code'), name='unique_valid_coupon_per_user'),
        ),
    ]
