# Generated by Django 3.2.4 on 2024-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('abandoned-cart', 'Abandoned Cart'), ('payment-pending', 'Payment Pending'), ('payment-expired', 'Payment Expired'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='cart', max_length=20, verbose_name='status'),
        ),
    ]
