# Generated by Django 3.2.4 on 2024-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(max_length=12, null=True, verbose_name='payment_reference'),
        ),
    ]
