# Generated by Django 3.2.4 on 2024-10-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_partial_checkouts'),
        ('marketplace', '0003_order_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPickupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_method', models.CharField(choices=[('pick-up-same-day', 'Pick Up in the same day'), ('keep-in-storage', 'Keep in storage'), ('delivery', 'Delivery')], max_length=16, verbose_name='pickup_method')),
                ('cooling_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_pickup_details', to='storage.coolingunit', verbose_name='order_item_pickup_details')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_details', to='marketplace.order', verbose_name='pickup_details')),
            ],
        ),
        migrations.AddIndex(
            model_name='orderpickupdetails',
            index=models.Index(fields=['order'], name='quicker_order_pickup_lookup'),
        ),
        migrations.AddConstraint(
            model_name='orderpickupdetails',
            constraint=models.UniqueConstraint(fields=('order', 'cooling_unit'), name='only_one_per_cooling_unit_and_order'),
        ),
    ]
