# Generated by Django 3.2.4 on 2024-10-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0025_alter_currency_fields'),
        ('marketplace', '0004_order_pickup_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDeliveryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('delivery_company_name', models.CharField(max_length=255, verbose_name='delivery_company_name')),
                ('contact_name', models.CharField(max_length=255, verbose_name='contact_name')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('company', models.ForeignKey(blank=True, null=False, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_contacts', to='user.company')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_company_delivery_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
