# Generated by Django 3.2.4 on 2024-10-10 12:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_companydeliverycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydeliverycontact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone'),
        ),
    ]
