# Generated by Django 3.2.4 on 2024-10-11 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_companydeliverycontact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12, null=True, verbose_name='payment_reference'), blank=True, default=list, size=None),
        ),
    ]
