# Generated by Django 3.2.4 on 2024-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20241011_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='status_changed_at'),
        ),
    ]
