# Generated by Django 3.2.4 on 2024-10-30 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_paystack_account__created_by_user_to_owned_by_user(apps, schema_editor):
    """
    Copies the value of created_by_user to owned_by_user for all existing
    PaystackAccount.
    """
    PaystackAccount = apps.get_model('marketplace', 'PaystackAccount')
    PaystackAccount.objects.all().update(owned_by_user=models.F('created_by_user'))

def copy_coupon__created_by_user_to_owned_by_user(apps, schema_editor):
    """
    Copies the value of created_by_user to owned_by_user for all existing
    Coupon.
    """
    Coupon = apps.get_model('marketplace', 'Coupon')
    Coupon.objects.all().update(owned_by_user=models.F('created_by_user'))

def copy_market_listed_crate_price_per_product__to_market_listed_crate_price(apps, schema_editor):
    """
    Copies the value of market_listed_crate_price_per_product to market_listed_crate_price for all existing
    MarketListedCratePrice.
    """
    MarketListedCrate = apps.get_model('marketplace', 'MarketListedCrate')
    MarketListedCratePrice = apps.get_model('marketplace', 'MarketListedCratePrice')

    market_listed_crates = MarketListedCrate.objects.all().prefetch_related('crate__produce__check_in__owner_user_id').annotate(
        created_by_user_id=models.F('crate__produce__check_in__owner_user_id')
    ).values('id', 'produce_price_per_kg', 'created_at', 'created_by_user_id')

    # Prepare list of MarketListedCratePrice instances for bulk_create
    crate_prices = [
        MarketListedCratePrice(
            market_listed_crate_id=item['id'],
            produce_price_per_kg=item['produce_price_per_kg'],
            created_at=item['created_at'],
            created_by_user_id=item['created_by_user_id'],
        ) for item in market_listed_crates
    ]

    # Insert one record for each MarketListedCrate instance
    MarketListedCratePrice.objects.bulk_create(crate_prices)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_notification_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0008_order_status_changed_at'),
    ]

    operations = [

        ##
        # Coupon
        ##
        migrations.AddField(
            model_name='coupon',
            name='owned_on_behalf_of_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_coupons', to='user.company'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='owned_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_coupon__created_by_user_to_owned_by_user, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coupon',
            name='owned_by_user',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, related_name='own_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),

        ##
        # MarketListedCrate
        ##

        migrations.CreateModel(
            name='MarketListedCratePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('produce_price_per_kg', models.FloatField(default=0, verbose_name='produce_price_per_kg')),
                ('market_listed_crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='marketplace.marketlistedcrate')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listing_crate_prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Copy the pricing data and remove the produce_price_per_kg field
        migrations.RunPython(copy_market_listed_crate_price_per_product__to_market_listed_crate_price, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='marketlistedcrate',
            name='produce_price_per_kg',
        ),

        ##
        # PaystackAccount
        ##

        migrations.RemoveConstraint(
            model_name='paystackaccount',
            name='unique_default_user_account',
        ),
        migrations.RemoveConstraint(
            model_name='paystackaccount',
            name='unique_default_company_account',
        ),
        migrations.RenameField(
            model_name='paystackaccount',
            old_name='company',
            new_name='owned_on_behalf_of_company',
        ),
        # add owned_by_user field
        migrations.AddField(
            model_name='paystackaccount',
            name='owned_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_paystack_accounts', to='user.user'),
            preserve_default=False,
        ),
        # Add migration so owned_by_user copies the value from created_by_user
        migrations.RunPython(copy_paystack_account__created_by_user_to_owned_by_user, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paystackaccount',
            name='owned_by_user',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='own_paystack_accounts', to='user.user'),
        ),

        # change created_by_user field
        migrations.AlterField(
            model_name='paystackaccount',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_paystack_accounts', to=settings.AUTH_USER_MODEL),
        ),

        # Change constraints
        migrations.AddConstraint(
            model_name='paystackaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_account', True), ('owned_on_behalf_of_company__isnull', True)), fields=('owned_by_user', 'is_default_account'), name='unique_default_user_account'),
        ),
        migrations.AddConstraint(
            model_name='paystackaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_account', True), ('owned_on_behalf_of_company__isnull', False)), fields=('owned_on_behalf_of_company', 'is_default_account'), name='unique_default_on_behalf_of_company_account'),
        ),
    ]
