# Generated by Django 3.2.4 on 2024-11-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0009_auto_20241030_1649'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paystackaccount',
            name='unique_default_on_behalf_of_company_account',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='on_behalf_of_company',
            new_name='owned_on_behalf_of_company',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='owned_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='paystackaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_account', True), ('owned_on_behalf_of_company__isnull', False)), fields=('owned_on_behalf_of_company', 'is_default_account'), name='unique_default_owned_on_behalf_of_company_account'),
        ),
    ]
