# Generated by Django 3.2.4 on 2024-11-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20241105_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketlistedcrate',
            name='cmp_last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cmp_last_updated_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cmp_last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cmp_last_updated_at'),
        ),
        migrations.AlterField(
            model_name='ordercrateitem',
            name='cmp_last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cmp_last_updated_at'),
        ),
    ]
