# Generated by Django 3.2.4 on 2024-12-17 11:00

from django.db import migrations, models

def copy_references_to_resulting_crates(apps, schema_editor):
    OrderCrateItem = apps.get_model('marketplace', 'OrderCrateItem')

    for order_crate_item in OrderCrateItem.objects.all():
        if order_crate_item.post_order_crate is None:
            continue

        order_crate_item.resulting_crates.add(order_crate_item.post_order_crate)
        order_crate_item.post_order_crate = None
        order_crate_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0041_alter_produce_cmp_last_updated_at'),
        ('marketplace', '0011_auto_20241107_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercrateitem',
            name='resulting_crates',
            field=models.ManyToManyField(related_name='ref_order_items', to='storage.Crate', verbose_name='resulting_crates'),
        ),
        migrations.RunPython(copy_references_to_resulting_crates),
        migrations.RemoveField(
                model_name='ordercrateitem',
                name='post_order_crate',
            ),
    ]
