# Generated by Django 3.2.4 on 2025-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0052_fix_electric_storage_system_values'),
        ('marketplace', '0013_update_bank_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydeliverycontact',
            name='cooling_units',
            field=models.ManyToManyField(
                blank=True,
                related_name='delivery_contacts',
                to='storage.CoolingUnit',
                verbose_name='cooling_units'
            ),
        ),
        migrations.AddField(
            model_name='companydeliverycontact',
            name='is_active',
            field=models.BooleanField(
                default=True,
                verbose_name='is_active'
            ),
        ),
    ]
