# Initial docker-compose config file which contains the common settings for all environments
services:
  ##
  # Dependencies
  ##
  db:
    image: postgis/postgis:12-3.3-alpine
    restart: always
    volumes:
      - base_postgres_data:/var/lib/postgresql/data
    networks:
      - base_network
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: base
      POSTGRES_USER: base
      POSTGRES_PASSWORD: base
    ports:
      - 54321:5432
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 10s
      timeout: 3s
      retries: 3

  valkey:
    restart: always
    image: 'valkey/valkey:7-alpine'
    networks:
      - base_network
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  ##
  # Gateway / reverse proxy for the underlaying services
  ##
  gateway:
    image: registry.gitlab.com/b1866/main-api/gateway:main
    platform: linux/amd64
    environment:
      URL_BASE_API: http://api.coldtivate.localhost
      URL_AIR_VCCA: http://air.coldtivate.localhost
      URL_FARMER_API: http://farmer.coldtivate.localhost
      URL_IMPACT_API: http://impact.coldtivate.localhost
      ACME_SERVER: https://acme-staging-v02.api.letsencrypt.org/directory
      FRONTEND_ORIGINS: app-e2e
    restart: always
    networks:
      - base_network
    links:
      - web:base_api
      - vcca_air_service:air_api
      - farmer_web:farmer_api
      - impact_dashboard_web:impact_api
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443

  ##
  # Web Services
  ##
  web:
    image: registry.gitlab.com/b1866/main-api/base-api:main
    platform: linux/amd64
    env_file: .env.e2e
    command: pipenv run gunicorn base.wsgi:application --workers 5 --bind 0.0.0.0:8000 --log-level=warning
    restart: always
    volumes:
      - base_api_media_data:/app/base/media
    links:
      - db
      - valkey
      - scraping_india
      - scraping_nigeria
    networks:
      - base_network
    environment:
      DJANGO_SETTINGS_MODULE: 'base.settings'
      PGHOST: db
      REDIS_HOST: valkey
      PRICE_PREDICTION_URL_INDIA: http://scraping_india:5000/prediction
      PRICE_PREDICTION_URL_NIGERIA: http://scraping_nigeria:5000/prediction

  celery:
    image: registry.gitlab.com/b1866/main-api/base-api:main
    platform: linux/amd64
    env_file: .env.e2e
    command: pipenv run celery -A base worker -B --scheduler django -l info --without-gossip --without-mingle
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: 'base.settings'
      PYTHONUNBUFFERED: 1
      DISPLAY: :1
      PGHOST: db
      REDIS_HOST: valkey
    links:
      - db
      - valkey
    networks:
      - base_network

  impact_dashboard_web:
    image: registry.gitlab.com/b1866/main-api/impact-dashboard-backend:main
    platform: linux/amd64
    env_file: .env.e2e
    restart: always
    networks:
      - base_network
    links:
      - db

  impact_dashboard_scheduler:
    image: registry.gitlab.com/b1866/main-api/impact-dashboard-backend-scheduler:main
    platform: linux/amd64
    env_file: .env.e2e
    restart: always
    networks:
      - base_network
    links:
      - db

  vcca_air_service:
    image: registry.gitlab.com/b1866/main-api/app-impact-reporting:main
    platform: linux/amd64
    env_file: .env.e2e
    restart: always
    networks:
      - base_network
    links:
      - db

  farmer_web:
    image: registry.gitlab.com/b1866/main-api/farmers-dashboard-backend:main
    platform: linux/amd64
    env_file: .env.e2e
    restart: always
    networks:
      - base_network
    links:
      - db

  farmer_scheduler:
    image: registry.gitlab.com/b1866/main-api/farmers-dashboard-backend-scheduler:main
    platform: linux/amd64
    env_file: .env.e2e
    restart: always
    networks:
      - base_network
    links:
      - db

  scraping_india:
    image: registry.gitlab.com/b1866/main-api/ml4-india:main
    platform: linux/amd64
    restart: always
    volumes:
      - ml4_india_data:/Scraping-module/data
    expose:
      - 5000
    networks:
      - base_network
    links:
      - valkey
    environment:
      FLASK_CACHE_TYPE: RedisCache
      FLASK_CACHE_REDIS_HOST: valkey
    command: pipenv run gunicorn prediction:app --workers 1 --bind 0.0.0.0:5000 --log-level=warning

  scraping_nigeria:
    image: registry.gitlab.com/b1866/main-api/ml4-nigeria:main
    platform: linux/amd64
    restart: always
    volumes:
      - ml4_nigeria_data:/Scraping-module/data
    expose:
      - 5000
    networks:
      - base_network
    links:
      - valkey
    environment:
      FLASK_CACHE_TYPE: RedisCache
      FLASK_CACHE_REDIS_HOST: valkey
    command: pipenv run gunicorn prediction:app --workers 1 --bind 0.0.0.0:5000 --log-level=warning

volumes:
  caddy_data:
  base_postgres_data:
  ml4_india_data:
  ml4_nigeria_data:
  base_api_media_data:

networks:
  base_network:
