# Generated by Django 3.2.4 on 2022-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_remove_crop_country"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="crop",
            field=models.ManyToManyField(
                blank=True,
                related_name="countryRelated",
                to="storage.Crop",
                verbose_name="company_crops",
            ),
        ),
    ]
