# Generated by Django 3.2.4 on 2022-07-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("CRATES", "Crates"), ("KILOGRAMS", "Kilograms")],
                max_length=32,
                null=True,
            ),
        ),
    ]
