# Generated by Django 3.2.4 on 2022-07-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_country_crop"),
        ("user", "0002_farmersurveycommodity_unit"),
    ]

    operations = []
