# Generated by Django 3.2.4 on 2022-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_merge_20220727_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("hi", "Hindi"), ("or", "Oriya")],
                max_length=2,
                null=True,
                verbose_name="language",
            ),
        ),
    ]
