# Generated by Django 3.2.4 on 2022-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=2, null=True, verbose_name="gender"),
        ),
    ]
