# Generated by Django 3.2.4 on 2022-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmersurveycommodity",
            name="location",
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="average_season_in_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="quantity_below_market_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="quantity_self_consumed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="quantity_sold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="quantity_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="farmersurveycommodity",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("KILOGRAMS", "Kilograms")],
                max_length=32,
                null=True,
            ),
        ),
    ]
