# Generated by Django 3.2.4 on 2022-10-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_update_farmersurveycommodity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="digital_twin",
            field=models.BooleanField(default=True),
        ),
    ]
