# Generated by Django 3.2.4 on 2022-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_company_digital_twin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="language",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notified",
        ),
        migrations.AddField(
            model_name="company",
            name="date_joined",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurvey",
            name="date_filled_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurvey",
            name="date_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="currency",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="currency",
            ),
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="date_filled_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="date_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitationuser",
            name="date_invitation_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
