# Generated by Django 3.2.4 on 2022-10-14 12:25

from django.db import migrations

# Generated by Django 3.2.4 on 2022-10-11 08:25


def update_dt_rows(apps, schema_editor):
    EncryptedCharModel = apps.get_model("user", "company")

    for row in EncryptedCharModel.objects.all():
        row.digital_twin = True
        row.save(update_fields=["digital_twin"])


class Migration(migrations.Migration):

    dependencies = [("user", "0008_auto_20221010_1439")]

    operations = [
        migrations.RunPython(update_dt_rows),
    ]
