# Generated by Django 3.2.4 on 2022-10-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_update_dt_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="specific_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
