# Generated by Django 3.2.4 on 2022-11-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_notification_specific_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="smartphone",
            field=models.BooleanField(default=False),
        ),
    ]
