# Generated by Django 3.2.4 on 2022-12-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_auto_20221108_1455"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
        migrations.AlterModelOptions(
            name="farmersurveycommodity",
            options={"verbose_name_plural": "farmer survey commodities"},
        ),
    ]
