# Generated by Django 3.2.4 on 2022-11-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_farmer_smartphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="country",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="user_code",
            field=models.CharField(null=True, blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="parent_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="parent_name"
            ),
        ),
    ]
