# Generated by Django 3.2.4 on 2022-11-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_auto_20221108_1455"),
        ("user", "0012_farmer_country_and_user_code"),
    ]

    operations = []
