# Generated by Django 3.2.4 on 2022-10-14 12:25

from django.db import migrations

# Generated by Django 3.2.4 on 2022-10-11 08:25


def update_ml4_fields(apps, schema_editor):
    company_model = apps.get_model("user", "company")

    for row in company_model.objects.all():
        if row.country.code == "IN":
            row.ML4_market = True
        else:
            row.ML4_market = False
        row.save(update_fields=["ML4_market"])


class Migration(migrations.Migration):

    dependencies = [("user", "0012_auto_20221207_1543")]

    operations = [
        migrations.RunPython(update_ml4_fields),
    ]
