# Generated by Django 3.2.4 on 2022-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0023_alter_sensorusermodel_cooling_unit"),
        ("user", "0013_merge_20221122_0808"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="worked_with_company",
                to="user.Company",
                verbose_name="worked_with_company",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="cooling_units",
            field=models.ManyToManyField(
                blank=True,
                related_name="cooling_unit_used",
                to="storage.CoolingUnit",
                verbose_name="cooling_unit_used",
            ),
        ),
    ]
