# Generated by Django 3.2.4 on 2022-12-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_auto_20221207_1543"),
        ("user", "0014_farmer_companies_and_cooling_units"),
    ]

    operations = []
