# Generated by Django 3.2.4 on 2023-01-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_update_ml4market_values"),
        ("user", "0015_merge_20221215_1430"),
    ]

    operations = []
