# Generated by Django 3.2.4 on 2023-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_merge_20230103_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("or", "Oriya"),
                    ("gu", "Gujarati"),
                ],
                max_length=2,
                null=True,
                verbose_name="language",
            ),
        ),
    ]
