# Generated by Django 3.2.4 on 2023-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmersurveycommodity",
            name="kg_in_unit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="kg_in_unit"
            ),
        ),
        migrations.AlterField(
            model_name="farmersurveycommodity",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KILOGRAMS", "Kilograms"),
                    ("CRATES", "Crates"),
                    ("BAGS", "Bags"),
                    ("SACKS", "Sacks"),
                    ("BASKETS", "Baskets"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
