# Generated by Django 3.2.4 on 2023-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_farmersurveycommodity_reason_for_loss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersurveycommodity",
            name="reason_for_loss",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Improper handling", "Improper harvest"),
                    ("Lack of cold storage", "inappropriate storage"),
                    ("Overproduction", "overproduction"),
                    ("Transportation damage", "Transport Damage"),
                    ("pest", "disease"),
                    ("Extreme weather conditions", "Extreme Weather"),
                    ("market prices too low", "Low Market Prices"),
                    ("other", "Other Reason"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
