# Generated by Django 3.2.4 on 2024-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_alter_farmersurveycommodity_reason_for_loss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("or", "Oriya"),
                    ("gu", "Gujarati"),
                    ("ig", "Igbo"),
                    ("yo", "Yoruba"),
                    ("ha", "Hausa"),
                ],
                max_length=2,
                null=True,
                verbose_name="language",
            ),
        ),
    ]
