# Generated by Django 3.2.4 on 2024-05-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=64, verbose_name='account_name')),
                ('account_number', models.CharField(max_length=64, verbose_name='account_number')),
                ('bank_name', models.CharField(max_length=64, verbose_name='bank_name')),
            ],
            options={
                'verbose_name_plural': 'bank_accounts',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_account', to='user.bankaccount', verbose_name='bank_account'),
        ),
    ]
