# Generated by Django 3.2.4 on 2024-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20240516_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('SENSOR_ERROR', 'Sensor error'), ('MARKET_SURVEY', 'Market survey'), ('TIME_TO_PICKUP', 'Time to pick up'), ('CHECKIN_EDITED', 'Checkin edited')], max_length=32),
        ),
    ]
