# Generated by Django 3.2.4 on 2024-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_currency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_public',
            field=models.BooleanField(default=False),
        ),
    ]
