# Generated by Django 3.2.4 on 2024-10-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20241010_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('SENSOR_ERROR', 'Sensor error'), ('MARKET_SURVEY', 'Market survey'), ('TIME_TO_PICKUP', 'Time to pick up'), ('CHECKIN_EDITED', 'Checkin edited'), ('ORDER_REQUIRES_MOVEMENT', 'Operational movement required')], max_length=32),
        ),
    ]
