# Generated by Django 3.2.4 on 2024-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_notification_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='flag_opt_out_from_marketplace_filter',
            field=models.BooleanField(default=False),
        ),
    ]
