# Generated by Django 3.2.4 on 2025-01-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_company_flag_opt_out_from_marketplace_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('SENSOR_ERROR', 'Sensor error'), ('MARKET_SURVEY', 'Market survey'), ('TIME_TO_PICKUP', 'Time to pick up'), ('CHECKIN_EDITED', 'Checkin edited'), ('ORDER_REQUIRES_MOVEMENT', 'Operational movement required'), ('LISTING_PRICE_UPDATED', 'Listing price updated')], max_length=32),
        ),
    ]
