# Generated by Django 3.2.4 on 2025-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi'), ('or', 'Oriya'), ('gu', 'Gujarati'), ('ig', 'Igbo'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('fr', 'French'), ('pt', 'Portugese'), ('ar', 'Arabic')], max_length=2, null=True, verbose_name='language'),
        ),
    ]
