# Generated by Django 3.2.4 on 2025-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('SENSOR_ERROR', 'Sensor error'), ('MARKET_SURVEY', 'Market survey'), ('TIME_TO_PICKUP', 'Time to pick up'), ('CHECKIN_EDITED', 'Checkin edited'), ('ORDER_REQUIRES_MOVEMENT', 'Operational movement required'), ('LISTING_PRICE_UPDATED', 'Listing price updated'), ('FARMER_SURVEY', 'Farmer survey'), ('CHECKOUT_EDITED', 'Checkout edited')], max_length=32),
        ),
    ]
