stages:
  - dependencies
  - test
  - build
  - deploy

image: ${CI_REGISTRY_IMAGE}:ci

###
## Template Scripts
###

.wait-for-emulator: &wait-for-emulator
  - while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do sleep 2; done; sleep 10 # Lets wait for the emulator a bit more, just to be sure it's ready

.yarn-install: &yarn-install
  - yarn config set cache-folder ~/.yarn
  - yarn install --frozen-lockfile

.bundler-install: &bundler-install
  - gem install bundler -v 2.4.22
  - bundler config set path ~/.bundler
  - bundler install

.trust-git-providers: &trust-git-providers
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

.git-secret-reveal: &git-secret-reveal
  - if [ "$GIT_SECRET_GPG_PATH" == "" ]; then echo "GIT SECRET GPG PATH NOT DEFINED"; exit 1; fi;
  - if [ "$GIT_SECRET_GPG_PASSWORD" == "" ]; then echo "GIT SECRET GPG PASSWORD NOT DEFINED"; exit 1; fi;
  - gpg --batch --passphrase "${GIT_SECRET_GPG_PASSWORD}" --import "$GIT_SECRET_GPG_PATH";
  - git secret reveal -p "$GIT_SECRET_GPG_PASSWORD";

###
## Caches
###

.yarn-cache: &yarn-cache
  key: yarn-cache
  policy: pull
  paths:
    - node_modules/
    - ~/.yarn
.gradle-cache: &gradle-cache
  key: gradle-cache
  policy: pull
  paths:
    - ~/.gradle/caches
    - ~/.gradle/wrapper
.android-cache: &android-cache
  key: android-cache
  policy: pull
  paths:
    - android/.gradle
    - android/build
    - android/app/build
.cocoapods-cache: &cocoapods-cache
  key:
    files:
      - ios/App/Podfile.lock
  policy: pull
  paths:
    - ios/App/Pods
.bundler-cache: &bundler-cache
  key: bundler-cache
  policy: pull
  paths:
    - ~/.bundler

# TODO: add Xcode project cache

###
## CI Dependencies
###

build ci image:
  stage: dependencies
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: '/certs'
  before_script:
    - command -v docker && docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker pull ${CI_REGISTRY_IMAGE}:ci || true
    - docker build --cache-from "${CI_REGISTRY_IMAGE}:ci" --tag "${CI_REGISTRY_IMAGE}:ci" --file ./docker/ci/Dockerfile.debian-based ./docker/ci
    - docker push "${CI_REGISTRY_IMAGE}:ci"
  only:
    # refs:
    #   - main
    #   - development
    #   - feat/*
    changes:
      - docker/ci/*

###
## Validation
###

# lint:
#   stage: validation
#   before_script:
#     - *yarn-install
#   script:
#     - yarn run lint

build android app e2e:
  extends: .build-android-app
  stage: test
  variables:
    LANE: e2e

    # API base urls
    BASE_API_BASE_URL: http://docker/base_api/
    AIR_PROD_BASE_URL: http://docker/air_api/
    IMPACT_BACKUP_BASE_URL: http://docker/impact_api/
    FARMER_IMPACT_BASE_URL: http://docker/farmer_api/
  when: manual
  before_script:
    - mv .env.e2e .env.e2e.bak;
    - cat .env.e2e.bak | grep -v "_BASE_URL" >> .env.e2e;
    - echo "BASE_API_BASE_URL=$BASE_API_BASE_URL" >> .env.e2e;
    - echo "AIR_PROD_BASE_URL=$AIR_PROD_BASE_URL" >> .env.e2e;
    - echo "IMPACT_BACKUP_BASE_URL=$IMPACT_BACKUP_BASE_URL" >> .env.e2e;
    - echo "FARMER_IMPACT_BASE_URL=$FARMER_IMPACT_BASE_URL" >> .env.e2e;
    - echo "## Resulting .env.e2e file:"
    - cat .env.e2e
  only:
    refs:
      - development
      - feat/e2e

run e2e tests with maestro:
  stage: test
  needs:
    - build android app e2e
  services:
    - name: docker:25.0.3-dind
      alias: docker
    - name: budtmo/docker-android:emulator_14.0_v2.15.0-p0
      alias: android-emulator
  variables:
    # Emulator variables
    EMULATOR_DEVICE: Samsung Galaxy S10
    WEB_VNC: true
    # Docker server variables
    FF_NETWORK_PER_BUILD: 'true'
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: /certs
    DOCKER_CERT_PATH: /certs/client
    DOCKER_TLS_VERIFY: '1'

    # API base urls
    BASE_API_BASE_URL: http://docker/base_api/
    AIR_PROD_BASE_URL: http://docker/air_api/
    IMPACT_BACKUP_BASE_URL: http://docker/impact_api/
    FARMER_IMPACT_BASE_URL: http://docker/farmer_api/
  before_script:
    # Install Maestro
    - curl -Ls "https://get.maestro.mobile.dev" | bash
    - export PATH="$PATH:$HOME/.maestro/bin"

    # Fix issue with path to the adb bin
    - export PATH="$PATH:/usr/local/android-sdk/platform-tools/"

    # Connect to the emulator
    - adb connect android-emulator:5555

    # Fix issue with access to the docker host
    - apt update && apt install -y inetutils-ping
    - export DOCKER_IP_ADDRESS=$(ping -c 1 docker | awk -F'[()]' '/PING/{print $2}')
    - *wait-for-emulator
    - adb root
    - adb remount /
    - adb reboot
    - *wait-for-emulator
    - adb root
    - adb remount /
    - adb pull /etc/hosts /tmp/hosts
    - echo "$DOCKER_IP_ADDRESS docker" >> /tmp/hosts
    - adb push /tmp/hosts /etc/hosts

    # Install app
    - adb install -r -g android/app/build/outputs/apk/e2e/app-e2e.apk

    # Setup e2e backend services
    - command -v docker && docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
    - ./docker/e2e/setup.sh

    # Uncomment for debugging purposes
    #- apt update && apt install -y tmate && tmate -F
  script:
    - maestro test .maestro
  only:
    refs:
      - development
      - feat/e2e

###
## Build
###

## Templates
.build-android-app:
  stage: build
  variables:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANE: build
  script:
    - *git-secret-reveal
    - *yarn-install
    - *bundler-install
    - export GRADLE_USER_HOME=$(pwd)/android/.gradle
    - export SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN"
    # - *trust-git-providers # mosano's runner already trust these
    # Build a release with fastlane and self generate the version Name and ID from some CI/CD env data-points
    - export VERSION_ID=${CI_COMMIT_REF_NAME}
    - if [ "$VERSION_ID" == "" ]; then git fetch --tags; export VERSION_ID=$(git describe --tags --abbrev=0 || echo "0.0.1"); fi;
    # Inject correct MAPBOX token into .env.x
    - sed -i "s|MAPBOX_ACCESS_TOKEN=.*|MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN|" ".env.$LANE"
    # Inject reCAPTCHA credentials
    - |
      if [ "$LANE" == "staging" ]; then
        sed -i "s|RECAPTCHA_SITE_KEY=.*|RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY_STAGING|" ".env.$LANE"
        sed -i "s|RECAPTCHA_BASE_URL=.*|RECAPTCHA_BASE_URL=$RECAPTCHA_BASE_URL_STAGING|" ".env.$LANE"
      elif [ "$LANE" == "production" ]; then
        sed -i "s|RECAPTCHA_SITE_KEY=.*|RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY_PRODUCTION|" ".env.$LANE"
        sed -i "s|RECAPTCHA_BASE_URL=.*|RECAPTCHA_BASE_URL=$RECAPTCHA_BASE_URL_PRODUCTION|" ".env.$LANE"
      fi
    - bundler exec fastlane android "$LANE" "version_id:$VERSION_ID"
  artifacts:
    paths:
      - android/app/build/outputs/
  cache:
    - <<: *yarn-cache
    - <<: *bundler-cache
      policy: pull-push
      key: bundler-cache-android
    - <<: *android-cache
      policy: pull-push
    - <<: *gradle-cache
      policy: pull-push

.build-ios-app:
  tags:
    # - saas-macos-medium-m1
    - macos
  image: macos-14-xcode-15
  stage: build
  variables:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANE: build
  script:
    - *yarn-install
    - *bundler-install
    - *trust-git-providers
    - eval $(ssh-agent -s)
    - chmod 0600 "$MATCH_GIT_PRIVATE_KEY_PATH"
    - ssh-add "$MATCH_GIT_PRIVATE_KEY_PATH"
    - echo "auth.token=$SENTRY_AUTH_TOKEN" > ios/sentry.properties
    - echo "defaults.org=coldtivate" >> ios/sentry.properties
    - echo "defaults.project=mobile-app" >> ios/sentry.properties
    - echo "defaults.url=https://sentry.io/" >> ios/sentry.properties
    # Build a release with fastlane and self generate the version Name and ID from some CI/CD env data-points
    - export VERSION_ID=${CI_COMMIT_REF_NAME}
    - if [ "$VERSION_ID" == "" ]; then git fetch --tags; export VERSION_ID=$(git describe --tags --abbrev=0 || echo "0.0.1"); fi;
    # Inject correct MAPBOX token into .env.x
    - sed -i '' "s|MAPBOX_ACCESS_TOKEN=.*|MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN|" ".env.$LANE"
    # Inject reCAPTCHA credentials
    - |
      if [ "$LANE" == "staging" ]; then
        sed -i '' "s|RECAPTCHA_SITE_KEY=.*|RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY_STAGING|" ".env.$LANE"
        sed -i '' "s|RECAPTCHA_BASE_URL=.*|RECAPTCHA_BASE_URL=$RECAPTCHA_BASE_URL_STAGING|" ".env.$LANE"
      elif [ "$LANE" == "production" ]; then
        sed -i '' "s|RECAPTCHA_SITE_KEY=.*|RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY_PRODUCTION|" ".env.$LANE"
        sed -i '' "s|RECAPTCHA_BASE_URL=.*|RECAPTCHA_BASE_URL=$RECAPTCHA_BASE_URL_PRODUCTION|" ".env.$LANE"
      fi
    - bundler exec fastlane ios "$LANE" "version_id:$VERSION_ID"
  artifacts:
    paths:
      - ios/build
  cache:
    - <<: *yarn-cache
    - <<: *bundler-cache
      policy: pull-push
      key: bundler-cache-ios
    - <<: *cocoapods-cache
      policy: pull-push

###
## Deployment
###

## Templates

## Jobs

build and publish android app staging:
  extends: .build-android-app
  variables:
    LANE: staging
  when: manual
  only:
    - tags

build and publish ios app staging:
  extends: .build-ios-app
  variables:
    NG_CONFIGURATION: staging
    LANE: staging
  when: manual
  only:
    - tags

## Jobs

build and publish android app production:
  extends: .build-android-app
  variables:
    LANE: production
  when: manual
  only:
    - tags

build and publish ios app production:
  extends: .build-ios-app
  variables:
    LANE: production
  when: manual
  only:
    - tags
