# Generated by Django 3.2.4 on 2022-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0, verbose_name="price")),
                ("paid", models.BooleanField(verbose_name="paid")),
                (
                    "selling_place",
                    models.CharField(
                        default=None, max_length=255, verbose_name="selling_place"
                    ),
                ),
                (
                    "selling_date",
                    models.CharField(
                        choices=[
                            ("TODAY", "Today"),
                            ("TOMORROW", "Tomorrow"),
                            ("OTHER", "Other"),
                        ],
                        default=None,
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selling_place",
                    models.CharField(max_length=255, verbose_name="selling_place"),
                ),
                ("price", models.FloatField(default=0, verbose_name="estimated_price")),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="currency",
                    ),
                ),
                (
                    "selling_metric",
                    models.CharField(
                        choices=[("CRATES", "Crates"), ("KILOGRAMS", "Kilograms")],
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True, verbose_name="date")),
                ("code", models.CharField(max_length=255, verbose_name="name")),
            ],
        ),
    ]
