# Generated by Django 3.2.4 on 2022-06-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operation", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movement_operator",
                to="user.operator",
                verbose_name="operator",
            ),
        ),
        migrations.AddField(
            model_name="marketsurvey",
            name="checkout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_checkout",
                to="operation.checkout",
                verbose_name="checkout",
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_movement",
                to="operation.movement",
                verbose_name="movement",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkin_farmer",
                to="user.farmer",
                verbose_name="farmer",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkin_movement",
                to="operation.movement",
                verbose_name="movement",
            ),
        ),
    ]
