# Generated by Django 3.2.4 on 2022-07-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="used_for_checkin",
            field=models.BooleanField(default=False),
        ),
    ]
