# Generated by Django 3.2.4 on 2022-09-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0004_market_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsurvey",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="market_survey_crop",
                to="storage.crop",
            ),
        ),
        migrations.AddField(
            model_name="marketsurvey",
            name="loss_in_kg",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketsurvey",
            name="selling_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="selling_date"
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="selling_date",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODAY", "Today"),
                    ("TOMORROW", "Tomorrow"),
                    ("OTHER", "Other"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="selling_place",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="selling_place",
            ),
        ),
        migrations.AlterField(
            model_name="marketsurvey",
            name="selling_metric",
            field=models.CharField(choices=[("KILOGRAMS", "Kilograms")], max_length=32),
        ),
    ]
