# Generated by Django 3.2.4 on 2022-10-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0005_update_marketsurvey_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("CREDIT_CARD", "Credit card"),
                    ("UPI", "UPI"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
