# Generated by Django 3.2.4 on 2022-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0006_checkout_payment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="selling_date",
        ),
        migrations.AddField(
            model_name="checkout",
            name="currency",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="currency",
            ),
        ),
        migrations.AddField(
            model_name="marketsurvey",
            name="date_filled_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
