# Generated by Django 3.2.4 on 2022-10-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0006_checkout_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="final_price",
            field=models.FloatField(default=0, verbose_name="final_price"),
        ),
        migrations.AddField(
            model_name="checkout",
            name="price_discount",
            field=models.FloatField(default=0, verbose_name="price_discount"),
        ),
    ]
