# Generated by Django 3.2.4 on 2022-10-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0007_auto_20221010_0915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="final_price",
            field=models.FloatField(default=0, verbose_name="final price"),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="price_discount",
            field=models.FloatField(default=0, verbose_name="price discount"),
        ),
    ]
