# Generated by Django 3.2.4 on 2022-10-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0007_auto_20221010_1838"),
        ("operation", "0008_auto_20221010_1007"),
    ]

    operations = []
