# Generated by Django 3.2.4 on 2022-10-11 08:25

from django.db import migrations


def update_market_survey_selling_place(apps, schema_editor):
    EncryptedCharModel = apps.get_model("operation", "marketsurvey")

    for row in EncryptedCharModel.objects.all():
        if row.selling_place == "local":
            selling_place = "local-market"
        elif row.selling_place == "farm":
            selling_place = "farm-gate"
        elif row.selling_place == "enam":
            selling_place = "enam-portal"
        else:
            selling_place = ""
        row.selling_place = selling_place
        row.save(update_fields=["selling_place"])


def update_currency_checkout(apps, schema_editor):
    EncryptedCharModel = apps.get_model("operation", "checkout")

    for row in EncryptedCharModel.objects.all():
        if row.currency is None:
            currency = row.movement.operator.company.currency
            row.currency = currency
            row.save(update_fields=["currency"])


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0009_merge_0007_auto_20221010_1838_0008_auto_20221010_1007")
    ]

    operations = [
        migrations.RunPython(
            update_market_survey_selling_place, update_currency_checkout
        ),
    ]
