# Generated by Django 3.2.4 on 2022-10-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "operation",
            "0010_updating_selling_place_market_survey_and_currency_checkout",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="selling_place",
        ),
    ]
