# Generated by Django 3.2.4 on 2022-10-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0011_remove_checkout_selling_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsurvey",
            name="market",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="market"
            ),
        ),
        migrations.AddField(
            model_name="marketsurvey",
            name="state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="state"
            ),
        ),
    ]
