# Generated by Django 3.2.4 on 2022-12-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prediction", "0001_initial"),
        ("operation", "0012_auto_20221020_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsurvey",
            name="market_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_market",
                to="prediction.market",
                verbose_name="market",
            ),
        ),
    ]
