# Generated by Django 3.2.4 on 2022-12-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0014_moving_markets_to_prediction_app"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketsurvey",
            name="market",
        ),
        migrations.RemoveField(
            model_name="marketsurvey",
            name="state",
        ),
        migrations.DeleteModel(
            name="Market",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
