# Generated by Django 3.2.4 on 2022-12-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0015_auto_20221209_1438"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketsurvey",
            old_name="market_link",
            new_name="market",
        ),
    ]
