# Generated by Django 3.2.4 on 2023-09-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0017_auto_20230914_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsurvey",
            name="selling_unit",
            field=models.CharField(
                choices=[("KILOGRAMS", "Kilograms")], max_length=32, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketsurveycheckout",
            unique_together={("checkout", "marketsurvey")},
        ),
        migrations.AlterModelTable(
            name="marketsurveycheckout",
            table="operation_marketsurvey_checkout",
        ),
    ]
