# Generated by Django 3.2.4 on 2023-10-02 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0026_produce_additional_info"),
        ("user", "0020_alter_farmersurveycommodity_reason_for_loss"),
        ("operation", "0018_auto_20230918_0106"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketsurveyPreprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "checkout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketsurvey_preprocess_checkout",
                        to="operation.checkout",
                        verbose_name="checkout",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketsurvey_preprocess_crop",
                        to="storage.crop",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketsurvey_preprocess_farmer",
                        to="user.farmer",
                        verbose_name="farmer",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketsurvey_preprocess_operator",
                        to="user.operator",
                        verbose_name="operator",
                    ),
                ),
            ],
        ),
    ]
