# Generated by Django 3.2.4 on 2023-11-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0019_marketsurveypreprocessing"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsurveypreprocessing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is_active"),
        ),
        migrations.AlterField(
            model_name="marketsurvey",
            name="selling_unit",
            field=models.CharField(
                choices=[
                    ("KILOGRAMS", "Kilograms"),
                    ("CRATES", "Crates"),
                    ("BAGS", "Bags"),
                    ("SACKS", "Sacks"),
                    ("BASKETS", "Baskets"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
