# Generated by Django 3.2.4 on 2024-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0020_auto_20231129_0448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsurvey",
            name="selling_unit",
            field=models.CharField(
                choices=[
                    ("KILOGRAMS", "Kilograms"),
                    ("CRATES", "Crates"),
                    ("BAGS", "Bags"),
                    ("SACKS", "Sacks"),
                    ("BASKETS", "Baskets"),
                    ("BOXES", "Boxes"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
