# Generated by Django 3.2.4 on 2024-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_alter_marketsurvey_selling_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit card'), ('UPI', 'UPI'), ('BANK', 'Bank')], default=None, max_length=20, null=True),
        ),
    ]
