# Generated by Django 3.2.4 on 2024-10-01 12:48

import base.utils.currencies
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_alter_checkin_ownership_from_farmer_to_user_and_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, validators=[base.utils.currencies.validate_currency], verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='marketsurvey',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, validators=[base.utils.currencies.validate_currency], verbose_name='currency'),
        ),
    ]
