# Generated by Django 3.2.4 on 2024-10-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0024_alter_currency_fields'),
        ('storage', '0035_alter_currency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='initiated_by',
            field=models.CharField(choices=[('ci', 'Check-in'), ('co', 'Check-out'), ('mo', 'Markerplace order')], default='ci', max_length=2),
            preserve_default=False,
        ),
    ]
