# Generated by Django 3.2.4 on 2024-10-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_partial_checkouts'),
        ('operation', '0025_integration_with_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='initiated_by',
            new_name='initiated_for',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit card'), ('UPI', 'UPI'), ('BANK', 'Bank'), ('COLDTIVATE', 'Coldtivate')], default=None, max_length=20, null=True),
        ),
    ]
