# Generated by Django 3.2.4 on 2024-10-30 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def checkout__set_payment_fields(apps, schema_editor):
    """
    Sets the payment fields for all existing Checkout instances.
    """
    Checkout = apps.get_model('operation', 'Checkout')
    Movement = apps.get_model('operation', 'Movement')

    # set 'DIRECT' to all checkouts (will overwrite with 'COLDTIVATE' later)
    Checkout.objects.all().update(payment_through='DIRECT')

    # Payment methods
    Checkout.objects.filter(
        models.Q(payment_type='BANK')
    ).update(payment_method='BANK_TRANSFER')
    Checkout.objects.filter(
        models.Q(payment_type='CREDIT_CARD') | models.Q(payment_type='CASH') | models.Q(payment_type='UPI')
    ).update(payment_method=models.F('payment_type'))

    # marketplace movements

    # Annotate using a subquery to check if any related checkins exist
    same_movement_has_checkin = models.Exists(
        Movement.objects.filter(checkin_movement__isnull=False, pk=models.OuterRef('movement_id'))
    )

    Checkout.objects.all().annotate(
        same_movement_has_checkin=same_movement_has_checkin,
    ).filter(
        same_movement_has_checkin=True,
    ).update(
        payment_gateway='PAYTACK',
        payment_method='CREDIT_CARD',
        payment_through='COLDTIVATE'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20241030_1649'),
        ('operation', '0026_auto_20241008_1120'),
    ]

    operations = [

        ##
        # Checkout
        ##
        migrations.AddField(
            model_name='checkout',
            name='cmp_last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cmp_last_updated_at'),
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='price_discount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='final_price',
            new_name='cmp_total_amount',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='price',
            new_name='cmp_total_cooling_fees_amount',
        ),

        # Payment fields
        migrations.AddField(
            model_name='checkout',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PAYTACK', 'Paystack'), ('STRIPE', 'Stripe')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit card'), ('QR_CODE', 'QR Code'), ('BANK_TRANSFER', 'Bank Transfer'), ('USSD', 'USSD'), ('OPAY', 'Opay'), ('UPI', 'UPI')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_through',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('COLDTIVATE', 'Coldtivate app')], default=None, max_length=20, null=True),
        ),
        migrations.RunPython(checkout__set_payment_fields, reverse_code=migrations.RunPython.noop),

        ##
        # Movement
        ##

        migrations.AddField(
            model_name='movement',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='marketplace.order', verbose_name='order'),
        ),
    ]
