# Generated by Django 3.2.4 on 2024-11-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_notification_event_type'),
        ('operation', '0027_auto_20241030_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment_type',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='owner_user',
            new_name='owned_by_user',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='owner_on_behalf_of_company',
            new_name='owned_on_behalf_of_company',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='owned_on_behalf_of_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_checkins', to='user.company', verbose_name='owned_on_behalf_of_company'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='operation.movement', verbose_name='movement'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cmp_total_amount',
            field=models.FloatField(default=0, verbose_name='cmp_total_amount'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cmp_total_cooling_fees_amount',
            field=models.FloatField(default=0, verbose_name='cmp_total_cooling_fees_amount'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='discount_amount',
            field=models.FloatField(default=0, verbose_name='discount_amount'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='operation.movement', verbose_name='movement'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_movements', to='user.operator', verbose_name='operator'),
        ),
    ]
