# Generated by Django 3.2.4 on 2024-10-05 13:26

from django.db import migrations, models
import django.db.models.deletion

def set_movement_initiated_for(apps, schema_editor):
    Checkout = apps.get_model('operation', 'Checkout')
    Movement = apps.get_model("operation", "Movement")

    # Update movements with the initiated_for set as "ci"
    # Set to "co" if there's a checkout and "mo" if it has a order_id
    for movement in Movement.objects.filter(initiated_for="ci"):
        if Checkout.objects.filter(movement=movement).exists():
            movement.initiated_for = "co"
        elif movement.order_id:
            movement.initiated_for = "mo"
        else:
            continue

        movement.save()

class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0028_auto_20241105_1449'),
    ]

    operations = [
        migrations.RunPython(set_movement_initiated_for, reverse_code=migrations.RunPython.noop),
    ]
