# Generated by Django 3.2.4 on 2025-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_recompute_all_checkouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PAYSTACK', 'Paystack'), ('STRIPE', 'Stripe')], default=None, max_length=20, null=True),
        ),
    ]
