# Generated by Django 3.2.4 on 2025-08-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0032_update_paytack_to_paystack_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketsurveycheckout',
            old_name='marketsurvey',
            new_name='market_survey',
        ),
        migrations.AlterUniqueTogether(
            name='marketsurveycheckout',
            unique_together={('checkout', 'market_survey')},
        ),
    ]
