# Generated by Django 3.2.4 on 2022-06-09 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoolingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "capacity_by_metric_tons",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="capacity_by_metric_tons",
                    ),
                ),
                (
                    "capacity_by_number_crates",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="capacity_by_number_crates",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[("CRATES", "Crates"), ("KILOGRAMS", "Kilograms")],
                        max_length=32,
                    ),
                ),
                ("sensor", models.BooleanField(default=False)),
                (
                    "cooling_unit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STORAGE", "Storage"),
                            ("TRANSPORTATION", "Transportation"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "time_pickup_to_customer",
                    models.FloatField(default=2, max_length=32),
                ),
                (
                    "crate_length",
                    models.FloatField(default=55.88, verbose_name="crate_length"),
                ),
                (
                    "crate_width",
                    models.FloatField(default=40.64, verbose_name="crate_width"),
                ),
                (
                    "crate_height",
                    models.FloatField(default=24.13, verbose_name="crate_height"),
                ),
                (
                    "crate_weight",
                    models.FloatField(default=25, verbose_name="crate_weight"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoolingUnitCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoolingUnitSpecifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(default=None, max_length=32)),
                (
                    "specification_type",
                    models.CharField(
                        choices=[
                            ("TEMPERATURE", "Temperature"),
                            ("HUMIDITY", "Humidity"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "datetime_stamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Stored"),
                            (2, "Acquired"),
                            (3, "Failed"),
                        ],
                        default=0,
                        verbose_name="status code",
                    ),
                ),
                ("weight", models.FloatField(default=None, verbose_name="weight")),
                (
                    "remaining_shelf_life",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="remaining_shelf_life",
                    ),
                ),
                (
                    "quality_dt",
                    models.FloatField(default=1, verbose_name="quality_computed_dt"),
                ),
                (
                    "temperature_dt",
                    models.FloatField(
                        default=290.4, verbose_name="temperature_computed_dt"
                    ),
                ),
                ("modified_dt", models.DateTimeField(blank=True, null=True)),
                (
                    "planned_days",
                    models.PositiveIntegerField(
                        blank=True, default=None, null=True, verbose_name="planned_days"
                    ),
                ),
                (
                    "estimated_price",
                    models.FloatField(default=0, verbose_name="estimated_price"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="crop_images"),
                ),
                (
                    "optimal_storage_temperature",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="optimal_storage_temperature",
                    ),
                ),
                (
                    "approximate_shelf_life",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="approximate_shelf_life",
                    ),
                ),
                (
                    "harvested_today",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=100,
                        null=True,
                        verbose_name="harvested_today",
                    ),
                ),
                (
                    "harvested_yesterday",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="harvested_yesterday"
                    ),
                ),
                (
                    "harvested_day_before_yesterday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="harvested_day_before_yesterday",
                    ),
                ),
                (
                    "harvested_before",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="harvested_before"
                    ),
                ),
                (
                    "size_selection_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="size_selection_1",
                    ),
                ),
                (
                    "size_selection_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="size_selection_2",
                    ),
                ),
                (
                    "size_selection_3",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="size_selection_3",
                    ),
                ),
                (
                    "digital_twin_identifier",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="dt_identifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="EcozenUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=32)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=150)),
                ("access_token", models.CharField(max_length=800)),
                ("last_entry", models.DateTimeField(blank=True, null=True)),
                ("notified", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=255, verbose_name="state"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="city"),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=255, verbose_name="street"),
                ),
                (
                    "street_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="street_number"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="zipCode"
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="latitude")),
                ("longitude", models.FloatField(verbose_name="longitude")),
            ],
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[("FIXED", "Fixed"), ("PERIODICITY", "Periodicity")],
                        max_length=32,
                    ),
                ),
                (
                    "fixed_rate",
                    models.FloatField(blank=True, verbose_name="fixed_rate"),
                ),
                (
                    "daily_rate",
                    models.FloatField(blank=True, verbose_name="daily_rate"),
                ),
                (
                    "weekly_rate",
                    models.FloatField(blank=True, verbose_name="weekly_rate"),
                ),
                (
                    "monthly_rate",
                    models.FloatField(blank=True, verbose_name="monthly_rate"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "harvest_date",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="harvest_date"
                    ),
                ),
                (
                    "initial_grade",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="initial_grade"
                    ),
                ),
                (
                    "size",
                    models.IntegerField(blank=True, null=True, verbose_name="size"),
                ),
                ("checkout_complete", models.BooleanField(default=False)),
                (
                    "check_in",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produce_check_in",
                        to="operation.checkin",
                        verbose_name="check_in",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produce_cooling_unit_crop",
                        to="storage.crop",
                        verbose_name="cooling_unit_crop",
                    ),
                ),
            ],
        ),
    ]
