# Generated by Django 3.2.4 on 2022-06-09 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operation", "0002_initial"),
        ("storage", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_provider_company",
                to="user.company",
                verbose_name="company",
            ),
        ),
        migrations.AddField(
            model_name="ecozenusermodel",
            name="cooling_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecozen_user_cooling_unit",
                to="storage.coolingunit",
                verbose_name="cooling_unit",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="country",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="crop_country",
                to="user.Country",
                verbose_name="country",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="crop_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_crop_type",
                to="storage.croptype",
                verbose_name="crop_type",
            ),
        ),
        migrations.AddField(
            model_name="crate",
            name="check_out",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crate_checkout",
                to="operation.checkout",
                verbose_name="crate_checkout",
            ),
        ),
        migrations.AddField(
            model_name="crate",
            name="cooling_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crate_cooling_unit",
                to="storage.coolingunit",
                verbose_name="cooling_unit",
            ),
        ),
        migrations.AddField(
            model_name="crate",
            name="produce",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crate_produce",
                to="storage.produce",
                verbose_name="produce",
            ),
        ),
        migrations.AddField(
            model_name="coolingunitspecifications",
            name="cooling_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specification_cooling_unit",
                to="storage.coolingunit",
                verbose_name="cooling_unit",
            ),
        ),
        migrations.AddField(
            model_name="coolingunitcrop",
            name="cooling_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crop_cooling_unit",
                to="storage.coolingunit",
                verbose_name="cooling_unit",
            ),
        ),
        migrations.AddField(
            model_name="coolingunitcrop",
            name="crop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cooling_unit_crop_crop",
                to="storage.crop",
                verbose_name="crop",
            ),
        ),
        migrations.AddField(
            model_name="coolingunitcrop",
            name="pricing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crop_pricing",
                to="storage.pricing",
                verbose_name="cooling_unit_crop-pricing",
            ),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cooling_units",
                to="storage.location",
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="operators",
            field=models.ManyToManyField(
                blank=True,
                related_name="cooling_unit_operators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="operators",
            ),
        ),
    ]
