# Generated by Django 3.2.4 on 2022-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="picture",
            field=models.FileField(blank=True, null=True, upload_to="produces_picture"),
        ),
    ]
