# Generated by Django 3.2.4 on 2022-07-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_produce_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="country",
        ),
    ]
