# Generated by Django 3.2.4 on 2022-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_remove_crop_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="crate",
            name="runDT",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
