# Generated by Django 3.2.4 on 2022-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_crate_rundt"),
    ]

    operations = [
        migrations.AddField(
            model_name="coolingunitspecifications",
            name="set_point_value",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
