# Generated by Django 3.2.4 on 2022-08-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_coolingunitspecifications_set_point_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coolingunitcrop",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
