# Generated by Django 3.2.4 on 2022-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_alter_coolingunitcrop_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="coolingunit",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
