# Generated by Django 3.2.4 on 2022-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0008_location_coolingunit_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coolingunit",
            name="cooling_unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FARM_GATE_STORAGE_ROOM", "Farm-gate storage room"),
                    ("MARKET_STORAGE_ROOM", "Market storage room"),
                    ("MOVABLE_UNIT", "Movable unit"),
                    ("OTHER", "Other"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
