# Generated by Django 3.2.4 on 2022-09-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_alter_coolingunit_cooling_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coolingunit",
            name="capacity_by_metric_tons",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                verbose_name="capacity_in_metric_tons",
            ),
        ),
        migrations.AlterField(
            model_name="coolingunit",
            name="capacity_by_number_crates",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="capacity_in_number_crates",
            ),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="food_capacity_in_metric_tons",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                verbose_name="food_capacity_in_metric_tons",
            ),
        ),
        migrations.RenameField(
            model_name="coolingunit",
            old_name="capacity_by_metric_tons",
            new_name="capacity_in_metric_tons",
        ),
        migrations.RenameField(
            model_name="coolingunit",
            old_name="capacity_by_number_crates",
            new_name="capacity_in_number_crates",
        ),
    ]
