# Generated by Django 3.2.4 on 2022-09-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_alter_coolingunit_food_capacity_in_metric_tons"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="activation_energy_constant",
            field=models.FloatField(
                blank=True, null=True, verbose_name="activation_energy_constant"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="dependent_constant",
            field=models.FloatField(
                blank=True, null=True, verbose_name="dependent_constant"
            ),
        ),
        migrations.AlterField(
            model_name="crate",
            name="quality_dt",
            field=models.FloatField(default=-1, verbose_name="quality_computed_dt"),
        ),
    ]
