# Generated by Django 3.2.4 on 2022-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0011_auto_20220920_1423"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crate",
            old_name="estimated_price",
            new_name="price_per_crate_per_pricing_type",
        ),
        migrations.AlterField(
            model_name="crate",
            name="price_per_crate_per_pricing_type",
            field=models.FloatField(
                default=0, verbose_name="price_per_crate_per_pricing_type"
            ),
        ),
        migrations.RemoveField(
            model_name="ecozenusermodel",
            name="last_entry",
        ),
        migrations.RemoveField(
            model_name="ecozenusermodel",
            name="notified",
        ),
        migrations.AddField(
            model_name="ecozenusermodel",
            name="date_sensor_first_linked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecozenusermodel",
            name="date_sensor_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="monthly_rate",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="weekly_rate",
        ),
        migrations.AddField(
            model_name="location",
            name="date_creation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="date_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
