# Generated by Django 3.2.4 on 2022-10-06 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storage", "0012_auto_20221006_1518"),
    ]

    operations = [
        migrations.AddField(
            model_name="coolingunit",
            name="date_creation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="date_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="occupancy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="occupancy_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OperatorAssignedCoolingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_assigned_to_cooling_unit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="date_operator_assigned",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_cooling_unit_operators",
                to="storage.OperatorAssignedCoolingUnit",
            ),
        ),
    ]
