# Generated by Django 3.2.4 on 2022-10-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_auto_20221006_1826"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ecozenusermodel",
            old_name="password",
            new_name="old_password",
        ),
    ]
