# Generated by Django 3.2.4 on 2022-10-14 10:35

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0014_rename_password_ecozenusermodel_old_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecozenusermodel",
            name="password",
            field=django_cryptography.fields.encrypt(
                models.CharField(default="", max_length=150)
            ),
        ),
    ]
