# Generated by Django 3.2.4 on 2022-10-14 10:35
from django.db import migrations


def forwards_encrypted_char(apps, schema_editor):
    EncryptedCharModel = apps.get_model("storage", "ecozenusermodel")

    for row in EncryptedCharModel.objects.all():
        row.password = row.old_password
        row.save(update_fields=["password"])


def reverse_encrypted_char(apps, schema_editor):
    EncryptedCharModel = apps.get_model("storage", "ecozenusermodel")

    for row in EncryptedCharModel.objects.all():
        row.old_password = row.password
        row.save(update_fields=["old_password"])


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0015_ecozenusermodel_password"),
    ]

    operations = [
        migrations.RunPython(forwards_encrypted_char, reverse_encrypted_char),
    ]
