# Generated by Django 3.2.4 on 2022-10-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0016_ecozenusermodel_password_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ecozenusermodel",
            name="old_password",
        ),
    ]
