# Generated by Django 3.2.4 on 2022-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0017_remove_ecozenusermodel_old_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="crate",
            name="currency",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="currency",
            ),
        ),
    ]
