# Generated by Django 3.2.4 on 2022-10-14 12:25

from django.db import migrations

# Generated by Django 3.2.4 on 2022-10-11 08:25


def update_currency_crate(apps, schema_editor):
    EncryptedCharModel = apps.get_model("storage", "crate")

    for row in EncryptedCharModel.objects.all():
        if row.currency is None:
            currency = row.cooling_unit.location.company.currency
            row.currency = currency
            row.save(update_fields=["currency"])


class Migration(migrations.Migration):

    dependencies = [("storage", "0018_crate_currency")]

    operations = [
        migrations.RunPython(update_currency_crate),
    ]
