# Generated by Django 3.2.4 on 2022-10-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0019_crate_currency_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crate",
            name="status",
        ),
    ]
