# Generated by Django 3.2.4 on 2022-11-15 09:42

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0020_remove_crate_status"),
    ]

    operations = [
        migrations.RenameModel("EcozenUserModel", "SensorUserModel"),
        migrations.AddField(
            model_name="SensorUserModel",
            name="type",
            field=models.CharField(max_length=32, default="ecozen"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="SensorUserModel",
            name="account_key",
            field=models.CharField(blank=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="SensorUserModel",
            name="channel_id",
            field=models.CharField(blank=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="SensorUserModel",
            name="machine_id",
            field=models.CharField(blank=True, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="SensorUserModel",
            name="username",
            field=models.CharField(blank=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="SensorUserModel",
            name="password",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, default="", max_length=150)
            ),
        ),
    ]
