# Generated by Django 3.2.4 on 2022-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0020_remove_crate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="coolingunit",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
