# Generated by Django 3.2.4 on 2022-11-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0021_alter_sensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorusermodel",
            name="field",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
