# Generated by Django 3.2.4 on 2022-11-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0021_alter_sensor"),
        ("storage", "0021_coolingunit_public"),
    ]

    operations = []
