# Generated by Django 3.2.4 on 2022-11-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0022_merge_0021_alter_sensor_0021_coolingunit_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorusermodel",
            name="cooling_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensor_user_cooling_unit",
                to="storage.coolingunit",
                verbose_name="cooling_unit",
            ),
        ),
    ]
