# Generated by Django 3.2.4 on 2022-11-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0022_ecozenusermodel_field"),
        ("storage", "0022_merge_0021_alter_sensor_0021_coolingunit_public"),
    ]

    operations = []
