# Generated by Django 3.2.4 on 2022-12-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0023_merge_20221129_1439"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coolingunitspecifications",
            options={"verbose_name_plural": "cooling unit specifications"},
        ),
        migrations.AlterField(
            model_name="sensorusermodel",
            name="cooling_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensor_user_cooling_unit",
                to="storage.coolingunit",
                verbose_name="cooling_unit",
            ),
        ),
    ]
