# Generated by Django 3.2.4 on 2022-12-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0023_alter_sensorusermodel_cooling_unit"),
        ("storage", "0024_auto_20221207_1543"),
    ]

    operations = []
