# Generated by Django 3.2.4 on 2023-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0025_merge_20221215_1429"),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="additional_info",
            field=models.CharField(
                max_length=255, null=True, verbose_name="additional_info"
            ),
        ),
    ]
