# Generated by Django 3.2.4 on 2024-01-25 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0026_produce_additional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="ethylene_production",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ethylene_production",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="ethylene_sensitivity",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ethylene_sensitivity",
            ),
        ),
        migrations.CreateModel(
            name="CoolingUnitPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "power_consumption_in_mt",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="power_consumption_in_mt",
                    ),
                ),
                (
                    "daily_room_wattage",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="daily_room_wattage",
                    ),
                ),
                (
                    "power_source_diesel_percent",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100.0)],
                        verbose_name="power_source_diesel_percent",
                    ),
                ),
                (
                    "power_source_grid_percent",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100.0)],
                        verbose_name="power_source_grid_percent",
                    ),
                ),
                (
                    "power_source_pv_percent",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100.0)],
                        verbose_name="power_source_pv_percent",
                    ),
                ),
                (
                    "power_source_biomass_percent",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100.0)],
                        verbose_name="power_source_biomass_percent",
                    ),
                ),
                (
                    "power_source_diesel_consumption_kwh",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="power_source_diesel_consumption_kwh",
                    ),
                ),
                (
                    "pv_panel_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="pv_panel_count"
                    ),
                ),
                (
                    "pv_panel_size",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="pv_panel_size"
                    ),
                ),
                (
                    "pv_panel_weight",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="pv_panel_weight",
                    ),
                ),
                (
                    "pv_panel_max_power",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="pv_panel_max_power",
                    ),
                ),
                (
                    "battery_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="battery_count"
                    ),
                ),
                (
                    "battery_size",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="battery_size"
                    ),
                ),
                (
                    "battery_capacity",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="battery_capacity",
                    ),
                ),
                (
                    "battery_max_current",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="battery_max_current",
                    ),
                ),
                (
                    "battery_peak_energy_storage",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="battery_peak_energy_storage ",
                    ),
                ),
                (
                    "refrigerant_type",
                    models.CharField(
                        choices=[
                            ("r290", "R290"),
                            ("R-410A", "r-410a"),
                            ("R-407c", "r-407c"),
                            ("R717", "r717"),
                            ("r600", "R600"),
                            ("R600A", "r600a"),
                            ("R601", "r601"),
                            ("r601a", "R601A"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "power_source",
                    models.CharField(
                        choices=[
                            ("generator", "GENERATOR"),
                            ("grid", "GRID"),
                            ("pvpanels", "PVPANELS"),
                            ("biomass", "BIOMASS"),
                            ("hybrid", "HYBRID"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "electricity_storage_system",
                    models.CharField(
                        choices=[
                            ("BATTERY", "battery"),
                            ("ice-pack", "thermal storage"),
                            ("HYBRID", "hybrid"),
                            ("NONE", "none"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "thermal_storage_method",
                    models.CharField(
                        choices=[
                            ("phase change material", "Phase Change Material"),
                            ("ice block storage", "Ice Block Storage"),
                            ("chilled water storage", "Chilled Water Storage"),
                            ("other", "OTHER"),
                            ("none", "None"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "cooling_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooling_unit_Power",
                        to="storage.coolingunit",
                    ),
                ),
            ],
        ),
    ]
