# Generated by Django 3.2.4 on 2024-02-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0027_auto_20240125_2310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="ethylene_production",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="ethylene_sensitivity",
        ),
        migrations.AlterField(
            model_name="coolingunitpower",
            name="battery_peak_energy_storage",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                verbose_name="battery_peak_energy_storage",
            ),
        ),
        migrations.AlterField(
            model_name="coolingunitpower",
            name="cooling_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cooling_unit_Power",
                to="storage.coolingunit",
                verbose_name="coolingUnit",
            ),
        ),
    ]
