# Generated by Django 3.2.4 on 2024-02-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0028_auto_20240202_0308"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coolingunitpower",
            name="battery_size",
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="room_height",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="room_height"
            ),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="room_length",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="room_length"
            ),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="room_weight",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="room_weight"
            ),
        ),
        migrations.AddField(
            model_name="coolingunit",
            name="room_width",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="room_width"
            ),
        ),
        migrations.AddField(
            model_name="coolingunitpower",
            name="amount_refrigerant",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="amount_refrigerant"
            ),
        ),
        migrations.AddField(
            model_name="coolingunitpower",
            name="battery_weight",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="battery_weight"
            ),
        ),
        migrations.AddField(
            model_name="coolingunitpower",
            name="room_insulator",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="room_insulator"
            ),
        ),
    ]
