# Generated by Django 3.2.4 on 2024-02-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0029_auto_20240213_0204"),
    ]

    operations = [
        migrations.AddField(
            model_name="coolingunitpower",
            name="battery_type",
            field=models.CharField(
                max_length=255, null=True, verbose_name="battery_type"
            ),
        ),
        migrations.AddField(
            model_name="coolingunitpower",
            name="pv_panel_type",
            field=models.CharField(
                max_length=255, null=True, verbose_name="battery_type"
            ),
        ),
    ]
