# Generated by Django 3.2.4 on 2024-02-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0030_auto_20240213_2357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coolingunitpower",
            name="electricity_storage_system",
            field=models.CharField(
                choices=[
                    ("battery", "BATTERY"),
                    ("thermal storage", "ice-pack"),
                    ("hybrid", "HYBRID"),
                    ("none", "NONE"),
                ],
                max_length=32,
            ),
        ),
    ]
