# Generated by Django 3.2.4 on 2024-02-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0031_alter_coolingunitpower_electricity_storage_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coolingunitpower",
            name="pv_panel_type",
            field=models.CharField(
                max_length=255, null=True, verbose_name="pv_panel_type"
            ),
        ),
    ]
