# Generated by Django 3.2.4 on 2024-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0032_alter_coolingunitpower_pv_panel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="crate",
            name="tag",
            field=models.CharField(max_length=255, null=True, verbose_name="tag"),
        ),
    ]
