# Generated by Django 3.2.4 on 2024-05-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0033_crate_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolingunit',
            name='editable_checkins',
            field=models.BooleanField(default=False),
        ),
    ]
