# Generated by Django 3.2.4 on 2024-10-01 12:48

import base.utils.currencies
from django.db import migrations, models, connection

DEPENDING_VIEW_NAME = "analytics_crate_movements"

def dump_and_clean_dependencies(apps, schema_editor):
    with connection.cursor() as cursor:
        # Drop the view
        cursor.execute("DROP VIEW IF EXISTS analytics_crate_movements")

class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0034_coolingunit_editable_checkins'),
    ]

    operations = [
        migrations.RunPython(dump_and_clean_dependencies),
        migrations.AlterField(
            model_name='crate',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, validators=[base.utils.currencies.validate_currency], verbose_name='currency'),
        ),
    ]
