# Generated by Django 3.2.4 on 2024-10-30 16:49

from django.db import migrations, models
from django.utils import timezone

def compute_initial_weight(apps, schema_editor):
    """
    Computes the initial weight of all existing Crate instances.
    """
    Crate = apps.get_model('storage', 'Crate')
    CratePartialCheckout = apps.get_model('storage', 'CratePartialCheckout')

    # Create a subquery to calculate the sum of weight_in_kg for each crate
    total_partial_weight = CratePartialCheckout.objects.filter(
        crate_id=models.OuterRef('pk')
    ).values('crate').annotate(
        total_weight=models.Sum('weight_in_kg')
    ).values('total_weight')

    # Update each crate's initial_weight with the sum of weight and partial weights
    Crate.objects.all().update(
        initial_weight=models.F('weight') + models.functions.Coalesce(models.Subquery(total_partial_weight), 0)
    )

def recompute_cooling_fees_on_partial_checkouts(apps, schema_editor):
    """
    Computes the cooling fees of all existing CratePartialCheckout instances.
    """
    CratePartialCheckout = apps.get_model('storage', 'CratePartialCheckout')
    Checkout = apps.get_model('operation', 'Checkout')
    Crate = apps.get_model('storage', 'Crate')
    CoolingUnitCrop = apps.get_model('storage', 'CoolingUnitCrop')


    partial_checkouts = CratePartialCheckout.objects.all().prefetch_related(
        'crate',
    ).annotate(
        checkin_date=models.F('crate__produce__check_in__movement__date'),
        checkout_date=models.F('checkout__movement__date'),

        cooling_fee_daily_rate=models.Subquery(
            CoolingUnitCrop.objects.filter(
                cooling_unit=models.OuterRef('crate__cooling_unit'),
                crop=models.OuterRef('crate__produce__crop'),
            ).values('pricing__daily_rate')[:1]
        ),
    ).order_by('checkout__movement__date')

    # calculate the cooling fees for all the partial checkouts
    for partial_checkout in partial_checkouts.iterator():
        crate = partial_checkout.crate

        checkout_date = partial_checkout.checkout_date or timezone.now()
        checkin_date = partial_checkout.checkin_date or checkout_date

        storage_duration_days = (checkout_date - checkin_date).days

        daily_rate = partial_checkout.cooling_fee_daily_rate or 0
        total_cooling_fees = daily_rate * storage_duration_days
        pending_in_cooling_fees = total_cooling_fees

        # deduct all the paid in cooling fees until that movement
        prior_partial_checkouts = CratePartialCheckout.objects.filter(
            crate=crate,
            checkout__movement__date__lt=checkout_date,
        ).order_by('checkout__movement__date')

        for prior_partial_checkout in prior_partial_checkouts.iterator():
            pending_in_cooling_fees -= prior_partial_checkout.cooling_fees

        # Update the partial_checkout.cooling_fees field
        partial_checkout.cooling_fees = pending_in_cooling_fees
        partial_checkout.save()


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_partial_checkouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='crate',
            name='initial_weight',
            field=models.FloatField(default=0, verbose_name='initial_weight'),
        ),

        migrations.RunPython(compute_initial_weight, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='cratepartialcheckout',
            name='cooling_fees',
            field=models.FloatField(default=0, verbose_name='cooling_fees'),
        ),

        migrations.RunPython(recompute_cooling_fees_on_partial_checkouts, reverse_code=migrations.RunPython.noop),
    ]
