# Generated by Django 3.2.4 on 2024-11-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0028_auto_20241105_1449'),
        ('storage', '0037_auto_20241030_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='check_in',
            new_name='checkin',
        ),
        migrations.AlterField(
            model_name='produce',
            name='checkin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='operation.checkin', verbose_name='checkin'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='initial_weight',
            field=models.FloatField(default=None, verbose_name='initial_weight'),
        ),
    ]
