# Generated by Django 3.2.4 on 2024-11-06 11:02

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0039_fix_fully_checked_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crate',
            old_name='fully_checked_out',
            new_name='cmp_fully_checked_out',
        ),

        migrations.AddField(
            model_name='crate',
            name='cmp_last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cmp_last_updated_at'),
        ),

        migrations.AddField(
            model_name='crate',
            name='cmp_total_due_in_cooling_fees',
            field=models.FloatField(default=0),
        ),

        migrations.AddField(
            model_name='crate',
            name='cmp_total_in_cooling_fees',
            field=models.FloatField(default=0),
        ),

        migrations.AddField(
            model_name='crate',
            name='cmp_total_paid_in_cooling_fees',
            field=models.FloatField(default=0),
        ),
    ]
