# Generated by Django 3.2.4 on 2024-11-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0040_crate_computed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='cmp_last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cmp_last_updated_at'),
        ),
    ]
