# Generated by Django 3.2.4 on 2024-10-30 16:49

from django.db import migrations, models
from django.utils import timezone

def compute_initial_weight(apps, schema_editor):
    """
    Computes the initial weight of all existing Crate instances.
    """
    Crate = apps.get_model('storage', 'Crate')
    CratePartialCheckout = apps.get_model('storage', 'CratePartialCheckout')

    # Create a subquery to calculate the sum of weight_in_kg for each crate
    total_partial_weight = CratePartialCheckout.objects.filter(
        crate_id=models.OuterRef('pk')
    ).values('crate').annotate(
        total_weight=models.Sum('weight_in_kg')
    ).values('total_weight')

    # Update each crate's initial_weight with the sum of weight and partial weights
    Crate.objects.all().update(
        initial_weight=models.F('weight') + models.functions.Coalesce(models.Subquery(total_partial_weight), 0)
    )

def set_currency_default_to_ngn_when_null(apps, schema_editor):
    """
    Sets the currency of all existing Crate instances to NGN when it is null.
    """
    Crate = apps.get_model('storage', 'Crate')

    # Fetch all crates with null currency
    crates = Crate.objects.filter(currency__isnull=True).select_related(
        'cooling_unit__location__company'
    )

    for crate in crates:
        # Set the currency to the company's currency or a default 'NGN'
        company_currency = getattr(crate.cooling_unit.location.company, 'currency', 'NGN')
        crate.currency = company_currency
        crate.save()

class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0041_alter_produce_cmp_last_updated_at'),
    ]

    operations = [
        migrations.RunPython(compute_initial_weight, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_currency_default_to_ngn_when_null, reverse_code=migrations.RunPython.noop),
    ]
