# Generated by Django 3.2.4 on 2024-10-30 16:49

from django.db import migrations

def compute_initial_weight(apps, schema_editor):
    """
    Computes the initial weight of all existing Crate instances.
    """
    Crate = apps.get_model('storage', 'Crate')

    # Context: there was a bug in the original codebase that allowed crates to be checkedin with weight set to zero.ArithmeticError
    # This migration fixes the crates that have the weight and initial_weight set to zero, as it impacts the logic on some of the endpoints.
    # Update each crate's initial_weight and weight to 1, whenever it was still zero
    Crate.objects.filter(initial_weight=0).update(
        initial_weight=1,
        weight=1,
        cmp_fully_checked_out=False,
    )

class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0042_recompute_initial_weight'),
    ]

    operations = [
        migrations.RunPython(compute_initial_weight, reverse_code=migrations.RunPython.noop),
    ]
