# Generated by Django 3.2.4 on 2025-02-28 15:59

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point

def populate_point_field(apps, schema_editor):
    Location = apps.get_model('storage', 'Location')
    for location in Location.objects.all():
        if location.latitude is not None and location.longitude is not None:
            location.point = Point(location.longitude, location.latitude, srid=4326)
            location.save()

class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0043_fix_crates_with_initial_weight_as_zero'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    BEGIN
                        CREATE EXTENSION IF NOT EXISTS postgis;
                    EXCEPTION
                        WHEN OTHERS THEN
                            -- Suppress error
                            RAISE NOTICE 'Could not create extension postgis: %', SQLERRM;
                    END;
                END
                $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.RunPython(populate_point_field),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=False, geography=True, null=False, srid=4326),
        ),
    ]
