# Generated by Django 3.2.4 on 2025-03-05 16:29

from django.db import migrations, models


def migrate_type_up(apps, schema_editor):
    SensorIntegration = apps.get_model('storage', 'SensorIntegration')

    for sensor in SensorIntegration.objects.all():
        if sensor.type == 'lora' or sensor.type == 'mote':
            sensor.type = 'figorr'
            sensor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0045_move_char_to_float_on_values'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE', reverse_sql='SET CONSTRAINTS ALL DEFERRED'),
        ##
        # Sensor Integration model
        ##
        migrations.RenameModel(
            old_name='SensorUserModel',
            new_name='SensorIntegration',
        ),
        migrations.RemoveField(
            model_name='sensorintegration',
            name='access_token',
        ),

        # Migrate old type format to new
        migrations.AlterField(
            model_name='sensorintegration',
            name='type',
            field=models.CharField(
                max_length=16,
                verbose_name='type',
                null=True,
            ),
        ),
        migrations.RunPython(
            migrate_type_up,
        ),
        migrations.AlterField(
            model_name='sensorintegration',
            name='type',
            field=models.CharField(
                choices=[
                    ('victron', 'Victron Energy'),
                    ('ubibot', 'Ubibot'),
                    ('figorr', 'Figorr'),
                    ('ecozen', 'Ecozen')
                ],
                max_length=16,
                verbose_name='type',
            ),
        ),

        ##
        # Add source_id field
        ##

        migrations.AddField(
            model_name='sensorintegration',
            name='source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED', reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
