# Generated by Django 3.2.4 on 2025-03-18 19:32

from django.db import migrations

from base.apps.storage.models.cooling_unit_specifications import \
    CoolingUnitSpecifications


def backfill_source_id(apps, schema_editor):
    SensorIntegration = apps.get_model("storage", "SensorIntegration")

    for sensor in SensorIntegration.objects.all():
        if not sensor.source_id:
            if sensor.type == "ecozen":
                sensor.source_id = sensor.machine_id or ""
            elif sensor.type == "figorr":
                sensor.source_id = f"{sensor.machine_id or ''}-{CoolingUnitSpecifications.SpecificationType.TEMPERATURE}"
            elif sensor.type == "ubibot":
                sensor.source_id = f"{sensor.channel_id or ''}-{CoolingUnitSpecifications.SpecificationType.TEMPERATURE}"
            sensor.save()

class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0046_sensory_integrations"),
    ]

    operations = [
        migrations.RunPython(backfill_source_id),
    ]
