# Generated by Django 3.2.4 on 2025-07-01 11:19

from django.db import migrations, models


def deduplicate_cooling_unit_specs(apps, schema_editor):
    CoolingUnitSpecifications = apps.get_model('storage', 'CoolingUnitSpecifications')
    from django.db.models import Count

    duplicates = (
        CoolingUnitSpecifications.objects
        .values('cooling_unit', 'datetime_stamp', 'specification_type')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for entry in duplicates:
        specs = CoolingUnitSpecifications.objects.filter(
            cooling_unit=entry['cooling_unit'],
            datetime_stamp=entry['datetime_stamp'],
            specification_type=entry['specification_type'],
        ).order_by('id')

        first = specs.first()
        if first:
            to_delete_qs = specs.exclude(id=first.id)
            count = to_delete_qs.count()
            if count > 0:
                print(f"Warning: {count} duplicates found for CU {entry['cooling_unit']} at {entry['datetime_stamp']} ({entry['specification_type']})")
                to_delete_qs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0048_alter_sensorintegrations_drop_fields'),
    ]

    operations = [
        migrations.RunPython(deduplicate_cooling_unit_specs),
        migrations.AddConstraint(
            model_name='coolingunitspecifications',
            constraint=models.UniqueConstraint(
                fields=['cooling_unit', 'datetime_stamp', 'specification_type'],
                name='unique_specification_per_cu_timestamp_type',
            ),
        ),
    ]
