export const ETHYLENE_LEVELS = {
  "N/A": {
    en: "N/A",
    hi: "लागू नहीं",
    or: "ପ୍ରଯୁଜ୍ୟ ନୁହେଁ",
    gu: "લાગુ પડતું નથી",
    fr: "N/A",
    pt: "N/A",
    yo: "Kò sí",
    ha: "Babu",
    ig: "N/A",
    ar: "غير متوفر",
  },
  "very low": {
    en: "very low",
    hi: "बहुत कम",
    or: "ବହୁତ କମ୍",
    gu: "ખૂબ જ નીચું",
    fr: "très faible",
    pt: "muito baixo",
    yo: "kéré púpọ̀",
    ha: "kadan kwarai",
    ig: "nnọọ ala",
    ar: "منخفض جدًا",
  },
  low: {
    en: "low",
    hi: "कम",
    or: "କମ୍",
    gu: "નીચું",
    fr: "faible",
    pt: "baixo",
    yo: "kéré",
    ha: "kadan",
    ig: "ala",
    ar: "منخفض",
  },
  moderate: {
    en: "moderate",
    hi: "मध्यम",
    or: "ମଧ୍ୟମ",
    gu: "મધ્યમ",
    fr: "modéré",
    pt: "moderado",
    yo: "àìpẹ́",
    ha: "matsakaici",
    ig: "nke etiti",
    ar: "متوسط",
  },
  high: {
    en: "high",
    hi: "अधिक",
    or: "ଅଧିକ",
    gu: "ઊંચું",
    fr: "élevé",
    pt: "alto",
    yo: "gíga",
    ha: "mai yawa",
    ig: "elu",
    ar: "عالي",
  },
  "very high": {
    en: "very high",
    hi: "बहुत अधिक",
    or: "ବହୁତ ଅଧିକ",
    gu: "ખૂબ જ ઊંચું",
    fr: "très élevé",
    pt: "muito alto",
    yo: "gíga púpọ̀",
    ha: "mai yawa sosai",
    ig: "nnọọ elu",
    ar: "عالي جدًا",
  },
};
export type EthyleneLevel = keyof typeof ETHYLENE_LEVELS;

export const CROP_STORAGE_TABLE_DATUMS = [
  {
    commodityName: "African star apple",
    optimalTemperature: "15 °C",
    storageLife: "15 days",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Apple",
    optimalTemperature: "-1.1-0 °C",
    storageLife: "3-6 months",
    ethyleneProduction: ETHYLENE_LEVELS["very high"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Avocado",
    optimalTemperature: "3-7 °C",
    storageLife: "2-4 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["high"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Banana",
    optimalTemperature: "13-15 °C",
    storageLife: "1-4 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Green beans",
    optimalTemperature: "4-7 °C",
    storageLife: "7-10 days",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Beetroot",
    optimalTemperature: "0 °C",
    storageLife: "4 month",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Capsicum (Bell Pepper)",
    optimalTemperature: "7-10 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Bitter Gourd",
    optimalTemperature: "10-12 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Bitter Leaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Bottle Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Broccoli",
    optimalTemperature: "0 °C",
    storageLife: "10-14 days",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Cabbage",
    optimalTemperature: "0°C",
    storageLife: "3-6 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Carrot",
    optimalTemperature: "0 °C",
    storageLife: "3-6 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Tapioca (Cassava)",
    optimalTemperature: "0-5 °C",
    storageLife: "1-2 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Cauliflower",
    optimalTemperature: "0 °C",
    storageLife: "3-4 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Bathua (Chenopodium)",
    optimalTemperature: "0-5 °C",
    storageLife: "1-2 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Colacasia",
    optimalTemperature: "7-10 °C",
    storageLife: "4 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Coriander",
    optimalTemperature: "0-1 °C",
    storageLife: "2 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Cucumber",
    optimalTemperature: "10-12 °C",
    storageLife: "7 days",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Drum stick",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Brinjal (Aubergine)",
    optimalTemperature: "10-12 °C",
    storageLife: "1-2 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Flat Beans",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Fluted pumpkin (leaves)",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Garlic",
    optimalTemperature: "-1-1 °C",
    storageLife: "6-7 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Ginger",
    optimalTemperature: "13 °C",
    storageLife: "6 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Grapes",
    optimalTemperature: "-0.5-0 °C",
    storageLife: "1-6 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Green Chilli",
    optimalTemperature: "5-10 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Green Gram",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Guava",
    optimalTemperature: "5-10 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Ivy Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Jackfruit",
    optimalTemperature: "13 °C",
    storageLife: "2-4 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Jute leaves",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Lemon",
    optimalTemperature: "10-13 °C",
    storageLife: "1-6 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Lemon basil",
    optimalTemperature: "10 °C",
    storageLife: "7 days",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Lettuce",
    optimalTemperature: "0 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Litchi",
    optimalTemperature: "1-2 °C",
    storageLife: "3-5 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Mango",
    optimalTemperature: "13 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Musk Melon",
    optimalTemperature: "\n5-10 °C",
    storageLife: "3-4 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Mint leaves",
    optimalTemperature: "0 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Methi",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Mushroom",
    optimalTemperature: "0 °C",
    storageLife: "7-14 days",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Oha/Ora Leaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Ladyfinger",
    optimalTemperature: "7-10 °C",
    storageLife: "7-10 days",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Onion",
    optimalTemperature: "0 °C",
    storageLife: "1-8 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Orange",
    optimalTemperature: "3-9 °C",
    storageLife: "3-8 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Papaya",
    optimalTemperature: "7-13 °C",
    storageLife: "1-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Peach",
    optimalTemperature: "-0.5-0 °C",
    storageLife: "2-4 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Pear",
    optimalTemperature: "-1.5 to -0.5 °C",
    storageLife: "2-7 months",
    ethyleneProduction: ETHYLENE_LEVELS["high"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Peas",
    optimalTemperature: "0 °C",
    storageLife: "1-2 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Pineapple",
    optimalTemperature: "7-13 °C",
    storageLife: "2-4 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Plantain",
    optimalTemperature: "13-15 °C",
    storageLife: "1-5 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Pointed Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Pomegranate",
    optimalTemperature: "5-7.2 °C",
    storageLife: "2-3 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Irish Potato",
    optimalTemperature: "4-8   °C",
    storageLife: "5-10 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Pumpkin",
    optimalTemperature: "12-15 °C",
    storageLife: "2-3 months",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Raspberry",
    optimalTemperature: "0 °C",
    storageLife: "2-5 days",
    ethyleneProduction: ETHYLENE_LEVELS["moderate"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Radish",
    optimalTemperature: "0 °C",
    storageLife: "1-2 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Ridge Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Roselle",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Scent leaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Spinach",
    optimalTemperature: "0 °C",
    storageLife: "10-14 days",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Spring onion",
    optimalTemperature: "0 °C",
    storageLife: "3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Strawberry",
    optimalTemperature: "0 °C",
    storageLife: "7-10 days",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["low"].en,
  },
  {
    commodityName: "Sweet Lime",
    optimalTemperature: "10-13 °C",
    storageLife: "1-6 months",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Taro root",
    optimalTemperature: "7-10 °C",
    storageLife: "4 months",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
  {
    commodityName: "Tomato",
    optimalTemperature: "8-13 °C",
    storageLife: "1-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["moderate"].en,
  },
  {
    commodityName: "Water Melon",
    optimalTemperature: "10-15 °C",
    storageLife: "2-3 weeks",
    ethyleneProduction: ETHYLENE_LEVELS["very low"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["high"].en,
  },
  {
    commodityName: "Waterleaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    ethyleneProduction: ETHYLENE_LEVELS["N/A"].en,
    ethyleneSensitivity: ETHYLENE_LEVELS["N/A"].en,
  },
];
export type CropStorageTableDatum = (typeof CROP_STORAGE_TABLE_DATUMS)[number];

export const CROP_LIST = [
  {
    commodityName: "Capsicum (Bell Pepper)",
    en: {
      IN: "Capsicum (Bell Pepper)",
      NG: "Bell Pepper",
      global: "Bell Pepper",
    },
    hi: "शिमला मिर्च",
    or: "ଲଙ୍କା",
    gu: "શિમલા મરચાં",
    pt: "Pimentão",
    fr: "Poivron",
    ha: "Tattasai",
    yo: "Ata rodo",
    ig: "Ose oyibo",
    ar: "فليفلة مدعبلة",
  },
  {
    commodityName: "Apple",
    en: {
      IN: "Apple",
      NG: "Apple",
      global: "Apple",
    },
    hi: "सेब",
    or: "ସେଓ",
    gu: "સફરજન",
    pt: "Maçã",
    fr: "Pomme",
    ha: "Apul",
    yo: "Apu",
    ig: "Apul",
    ar: "تفاح",
  },
  {
    commodityName: "Banana",
    en: {
      IN: "Banana",
      NG: "Banana",
      global: "Banana",
    },
    hi: "केला",
    or: "କଦଳୀ",
    gu: "કેળું",
    pt: "Banana",
    fr: "Banane",
    ha: "Ayaba",
    yo: "Ogede",
    ig: "Unere",
    ar: "موز",
  },
  {
    commodityName: "Beans",
    en: {
      IN: "Beans",
      NG: "Beans",
      global: "Beans",
    },
    hi: "राजमा",
    or: "ବରବଟି",
    gu: "રાજમા",
    pt: "Feijões",
    fr: "Haricots",
    ha: "Wake",
    yo: "Ewa",
    ig: "Agwa",
    ar: "فول",
  },
  {
    commodityName: "Green beans",
    en: {
      IN: "Green beans",
      NG: "Green beans",
      global: "Green beans",
    },
    hi: "हरी फलियां",
    or: "ସବୁଜ ବରବଟି",
    gu: "શીરીંગા ફણસી (શાકભાજી)",
    pt: "Vagens",
    fr: "Haricots verts",
    ha: "Wake mai kore",
    yo: "Ewa tutu",
    ig: "Agwa ndu",
    ar: "فاصوليا خضراء",
  },
  {
    commodityName: "Beetroot",
    en: {
      IN: "Beetroot",
      NG: "Beetroot",
      global: "Beetroot",
    },
    hi: "चुकंदर",
    or: "ବୀଟ୍",
    gu: "બીટ",
    pt: "Beterraba",
    fr: "Betterave",
    ha: "Bitrus",
    yo: "Isu biti",
    ig: "Biturutu",
    ar: "البنجر",
  },
  {
    commodityName: "Bitter Gourd",
    en: {
      IN: "Bitter Gourd",
      NG: "Bitter Melon",
      global: "Bitter Gourd",
    },
    hi: "करेला",
    or: "କଲରା",
    gu: "કારેલા",
    pt: "Melão amargo",
    fr: "Melon amer",
    ha: "Garafuni mai daci",
    yo: "Ejinrin",
    ig: "Ugu olu",
    ar: "القرع المر",
  },
  {
    commodityName: "Bottle Gourd",
    en: {
      IN: "Bottle Gourd",
      NG: "Calabash (Gourd)",
      global: "Bottle Gourd",
    },
    hi: "लौकी",
    or: "ଲାଉ",
    gu: "દૂધી",
    pt: "Cabaça",
    fr: "Calebasse",
    ha: "Duma",
    yo: "Igba",
    ig: "Ugboguru",
    ar: "قرع الزجاجة",
  },
  {
    commodityName: "Broccoli",
    en: {
      IN: "Broccoli",
      NG: "Broccoli",
      global: "Broccoli",
    },
    hi: "ब्रोकली",
    or: "ବ୍ରୋକୋଲି",
    gu: "બ્રોકોલી",
    pt: "Brócolis",
    fr: "Brocoli",
    ha: "Brokoli",
    yo: "Brokoli",
    ig: "Brokoli",
    ar: "بروكلي",
  },
  {
    commodityName: "Cabbage",
    en: {
      IN: "Cabbage",
      NG: "Cabbage",
      global: "Cabbage",
    },
    hi: "पत्ता गोभी",
    or: "ବନ୍ଧାକୋବି",
    gu: "કોબી",
    pt: "Repolho",
    fr: "Chou",
    ha: "Kabej",
    yo: "Efo kabeeji",
    ig: "Kabej",
    ar: "لهانة",
  },
  {
    commodityName: "Carrot",
    en: {
      IN: "Carrot",
      NG: "Carrot",
      global: "Carrot",
    },
    hi: "गाजर",
    or: "ଗାଜର",
    gu: "ગાજર",
    pt: "Cenoura",
    fr: "Carotte",
    ha: "Karoti",
    yo: "Karot",
    ig: "Karoti",
    ar: "جزر",
  },
  {
    commodityName: "Tapioca (Cassava)",
    en: {
      IN: "Tapioca (Cassava)",
      NG: "Cassava",
      global: "Cassava",
    },
    hi: "साबूदाना (कसावा)",
    or: "ମାଣିଆ",
    gu: "કસાવા",
    pt: "Mandioca",
    fr: "Manioc",
    ha: "Rogo",
    yo: "Ege",
    ig: "Akpu",
    ar: "التابيوكا (الكسافا)",
  },
  {
    commodityName: "Cauliflower",
    en: {
      IN: "Cauliflower",
      NG: "Cauliflower",
      global: "Cauliflower",
    },
    hi: "फूलगोभी",
    or: "ଫୁଲକୋବି",
    gu: "ફૂલકોબી",
    pt: "Couve-flor",
    fr: "Chou-fleur",
    ha: "Kaliflawa",
    yo: "Efo kaliflawa",
    ig: "Kaliflawa",
    ar: "قرنبيط",
  },
  {
    commodityName: "Bathua (Chenopodium)",
    en: {
      IN: "Bathua (Chenopodium)",
      NG: "Chenopodium",
      global: "Chenopodium",
    },
    hi: "बथुआ",
    or: "ବଥୁଆ",
    gu: "ચીલ ભાજી",
    pt: "Chenopódio",
    fr: "Chénopode",
    ha: "Batua",
    yo: "Efo batua",
    ig: "Batua",
    ar: "باثوا (تشينوبوديوم)",
  },
  {
    commodityName: "Colacasia",
    en: {
      IN: "Colocasia",
      NG: "Cocoyam",
      global: "Taro",
    },
    hi: "अरबी",
    or: "ସାରୁ",
    gu: "અરવી",
    pt: "Inhame",
    fr: "Taro",
    ha: "Gwaza",
    yo: "Koko",
    ig: "Ede",
    ar: "كولاكاسيا",
  },
  {
    commodityName: "Coriander",
    en: {
      IN: "Coriander",
      NG: "Coriander",
      global: "Coriander",
    },
    hi: "धनिया",
    or: "ଧନିଆ",
    gu: "કોથમીર",
    pt: "Coentro",
    fr: "Coriandre",
    ha: "Korianda",
    yo: "Efo korianda",
    ig: "Korianda",
    ar: "كسبرة",
  },
  {
    commodityName: "Cucumber",
    en: {
      IN: "Cucumber",
      NG: "Cucumber",
      global: "Cucumber",
    },
    hi: "खीरा",
    or: "କାକୁଡ଼ି",
    gu: "કાકડી",
    pt: "Pepino",
    fr: "Concombre",
    ha: "Kokumba",
    yo: "Apalá",
    ig: "Okumkom",
    ar: "خيار",
  },
  {
    commodityName: "Dairy",
    en: {
      IN: "Dairy",
      NG: "Dairy",
      global: "Dairy",
    },
    hi: "डेयरी",
    or: "ଦୁଗ୍ଧଜାତ",
    gu: "દૂધની બનાવટ",
    pt: "Laticínios",
    fr: "Produits laitiers",
    ha: "Madara",
    yo: "Wara",
    ig: "Mmiri ara",
    ar: "مذكرة",
  },
  {
    commodityName: "Drum stick",
    en: {
      IN: "Drumstick",
      NG: "Moringa",
      global: "Moringa",
    },
    hi: "सहजन",
    or: "ସଜନା",
    gu: "સરગવો",
    pt: "Moringa",
    fr: "Moringa",
    ha: "Zogale",
    yo: "Ewe ile",
    ig: "Okwuru oyibo",
    ar: "عصا الطبل",
  },
  {
    commodityName: "Brinjal (Aubergine)",
    en: {
      IN: "Brinjal",
      NG: "Garden Egg",
      global: "Eggplant",
    },
    hi: "बैंगन",
    or: "ବାଇଗଣ",
    gu: "રીંગણ",
    pt: "Berinjela",
    fr: "Aubergine",
    ha: "Gauta",
    yo: "Ìgbá",
    ig: "Anyara",
    ar: "باذنجان",
  },
  {
    commodityName: "Fish",
    en: {
      IN: "Fish",
      NG: "Fish",
      global: "Fish",
    },
    hi: "मछली",
    or: "ମାଛ",
    gu: "માછલી",
    pt: "Peixe",
    fr: "Poisson",
    ha: "Kifi",
    yo: "Eja",
    ig: "Azu",
    ar: "سمك",
  },
  {
    commodityName: "Flat Beans",
    en: {
      IN: "Flat Beans",
      NG: "Flat Beans",
      global: "Flat Beans",
    },
    hi: "सेम",
    or: "ଚିପଟା ବରବଟି",
    gu: "પાપડી",
    pt: "Feijão-verde",
    fr: "Haricots plats",
    ha: "Wake mai faɗi",
    yo: "Ewa pepele",
    ig: "Agwa pịa",
    ar: "الفاصوليا المسطحة",
  },
  {
    commodityName: "Flowers",
    en: {
      IN: "Flowers",
      NG: "Flowers",
      global: "Flowers",
    },
    hi: "फूल",
    or: "ଫୁଲ",
    gu: "ફૂલ",
    pt: "Flores",
    fr: "Fleurs",
    ha: "Furanni",
    yo: "Odòdó",
    ig: "Ufe",
    ar: "الزهور",
  },
  {
    commodityName: "Garlic",
    en: {
      IN: "Garlic",
      NG: "Garlic",
      global: "Garlic",
    },
    hi: "लहसुन",
    or: "ରସୁଣ",
    gu: "લસણ",
    pt: "Alho",
    fr: "Ail",
    ha: "Tafarnuwa",
    yo: "Àlùbọ́sà",
    ig: "Ayụ",
    ar: "ثوم",
  },
  {
    commodityName: "Ginger",
    en: {
      IN: "Ginger",
      NG: "Ginger",
      global: "Ginger",
    },
    hi: "अदरक",
    or: "ଆଦା",
    gu: "આદુ",
    pt: "Gengibre",
    fr: "Gingembre",
    ha: "Citta",
    yo: "Atale",
    ig: "Jinja",
    ar: "زنجبيل",
  },
  {
    commodityName: "Grapes",
    en: {
      IN: "Grapes",
      NG: "Grapes",
      global: "Grapes",
    },
    hi: "अंगूर",
    or: "ଅଙ୍ଗୁର",
    gu: "દ્રાક્ષ",
    pt: "Uvas",
    fr: "Raisins",
    ha: "Inabi",
    yo: "Èso àjàrà",
    ig: "Uva",
    ar: "العنب",
  },
  {
    commodityName: "Green Chilli",
    en: {
      IN: "Green Chilli",
      NG: "Green Pepper",
      global: "Green Chili",
    },
    hi: "हरी मिर्च",
    or: "କଞ୍ଚା ଲଙ୍କା",
    gu: "લીલા મરચાં",
    pt: "Pimenta verde",
    fr: "Piment vert",
    ha: "Barkono mai kore",
    yo: "Ata jíjẹ́",
    ig: "Ose ndu",
    ar: "الفلفل الأخضر",
  },
  {
    commodityName: "Green Gram",
    en: {
      IN: "Green Gram",
      NG: "Mung Bean",
      global: "Mung Bean",
    },
    hi: "मूंग",
    or: "ମୁଗ",
    gu: "મગ",
    pt: "Feijão mungo",
    fr: "Haricot mungo",
    ha: "Wake mai kore",
    yo: "Ewa tútù",
    ig: "Agwa ndu",
    ar: "الحمص الأخضر",
  },
  {
    commodityName: "Guava",
    en: {
      IN: "Guava",
      NG: "Guava",
      global: "Guava",
    },
    hi: "अमरूद",
    or: "ପିଜୁଳି",
    gu: "જામફળ",
    pt: "Goiaba",
    fr: "Goyave",
    ha: "Gwaba",
    yo: "Gọọbà",
    ig: "Guava",
    ar: "الجوافة",
  },
  {
    commodityName: "Irish Potato",
    en: {
      IN: "Potato",
      NG: "Irish Potato",
      global: "Potato",
    },
    hi: "आलू",
    or: "ଆଳୁ",
    gu: "બટાટા",
    pt: "Batata",
    fr: "Pomme de terre",
    ha: "Dankali",
    yo: "Isu àlùbọ́sà",
    ig: "Ji Bekee",
    ar: "البطاطس اعتيادية",
  },
  {
    commodityName: "Ivy Gourd",
    en: {
      IN: "Ivy Gourd",
      NG: "Little Gourd",
      global: "Ivy Gourd",
    },
    hi: "कुंदरु",
    or: "କୁନ୍ଦୁରି",
    gu: "ઘીલોડી",
    pt: "Cabaça de Hera",
    fr: "Gourde de lierre",
    ha: "Garafuni",
    yo: "Ẹfọ́ yorọ",
    ig: "Ahihia ugboguru",
    ar: "قرع اللبلاب",
  },
  {
    commodityName: "Jackfruit",
    en: {
      IN: "Jackfruit",
      NG: "Jackfruit",
      global: "Jackfruit",
    },
    hi: "कटहल",
    or: "ପଣସ",
    gu: "ફણસ",
    pt: "Jaca",
    fr: "Jacquier",
    ha: "Gwanda",
    yo: "Ọ̀pẹ́",
    ig: "Ukwa oyibo",
    ar: "الجاك فروت",
  },
  {
    commodityName: "Lemon",
    en: {
      IN: "Lemon",
      NG: "Lemon",
      global: "Lemon",
    },
    hi: "नींबू",
    or: "ଲେମ୍ବୁ",
    gu: "લીંબુ",
    pt: "Limão",
    fr: "Citron",
    ha: "Lemu",
    yo: "Ọsàn wewe",
    ig: "Lemonu",
    ar: "ليمون",
  },
  {
    commodityName: "Lettuce",
    en: {
      IN: "Lettuce",
      NG: "Lettuce",
      global: "Lettuce",
    },
    hi: "सलाद पत्ता",
    or: "ଲେଟସ୍",
    gu: "લેટીસ",
    pt: "Alface",
    fr: "Laitue",
    ha: "Latis",
    yo: "Lẹ́túsì",
    ig: "Letusi",
    ar: "خَسّ",
  },
  {
    commodityName: "Litchi",
    en: {
      IN: "Litchi",
      NG: "Lychee",
      global: "Lychee",
    },
    hi: "लीची",
    or: "ଲିଚୁ",
    gu: "લીચી",
    pt: "Lichia",
    fr: "Litchi",
    ha: "Litchi",
    yo: "Lítíshì",
    ig: "Litchi",
    ar: "ليتشي",
  },
  {
    commodityName: "Mango",
    en: {
      IN: "Mango",
      NG: "Mango",
      global: "Mango",
    },
    hi: "आम",
    or: "ଆମ୍ବ",
    gu: "કેરી",
    pt: "Manga",
    fr: "Mangue",
    ha: "Mangwaro",
    yo: "Mangoro",
    ig: "Mangoro",
    ar: "مانجو",
  },
  {
    commodityName: "Meat",
    en: {
      IN: "Meat",
      NG: "Meat",
      global: "Meat",
    },
    hi: "मांस",
    or: "ମାଂସ",
    gu: "માંસ",
    pt: "Carne",
    fr: "Viande",
    ha: "Nama",
    yo: "Ẹran",
    ig: "Anụ",
    ar: "لحم",
  },
  {
    commodityName: "Musk Melon",
    en: {
      IN: "Musk Melon",
      NG: "Egusi Melon",
      global: "Musk Melon",
    },
    hi: "खरबूजा",
    or: "ତରଭୁଜ",
    gu: "શક્કરટેટી",
    pt: "Melão",
    fr: "Melon",
    ha: "Guna",
    yo: "Ẹgúsí",
    ig: "Egusi",
    ar: "مسك البطيخ",
  },
  {
    commodityName: "Mint leaves",
    en: {
      IN: "Mint leaves",
      NG: "Mint leaves",
      global: "Mint leaves",
    },
    hi: "पुदीना",
    or: "ପୁଦିନା",
    gu: "ફુદીનો",
    pt: "Hortelã",
    fr: "Menthe",
    ha: "Na'ana'a",
    yo: "Ewé minti",
    ig: "Mint",
    ar: "أوراق النعناع",
  },
  {
    commodityName: "Methi",
    en: {
      IN: "Fenugreek",
      NG: "Moringa leaves",
      global: "Fenugreek",
    },
    hi: "मेथी",
    or: "ମେଥି",
    gu: "મેથી",
    pt: "Feno-grego",
    fr: "Fenugrec",
    ha: "Ganyen zogale",
    yo: "Ewé Moringa",
    ig: "Akwụkwọ moringa",
    ar: "الميثي (أوراق المورينجا)",
  },
  {
    commodityName: "Mushroom",
    en: {
      IN: "Mushroom",
      NG: "Mushroom",
      global: "Mushroom",
    },
    hi: "मशरूम",
    or: "ଛତୁ",
    gu: "મશરૂમ",
    pt: "Cogumelo",
    fr: "Champignon",
    ha: "Naman kaza",
    yo: "Ọlọ́",
    ig: "Ero",
    ar: "فطر",
  },
  {
    commodityName: "Ladyfinger",
    en: {
      IN: "Okra",
      NG: "Okra",
      global: "Okra",
    },
    hi: "भिंडी",
    or: "ଭିଣ୍ଡି",
    gu: "ભીંડો",
    pt: "Quiabo",
    fr: "Gombo",
    ha: "Kubewa",
    yo: "Ilá",
    ig: "Okwuru",
    ar: "بامية",
  },
  {
    commodityName: "Onion",
    en: {
      IN: "Onion",
      NG: "Onion",
      global: "Onion",
    },
    hi: "प्याज",
    or: "ପିଆଜ",
    gu: "ડુંગળી",
    pt: "Cebola",
    fr: "Oignon",
    ha: "Albasa",
    yo: "Àlùbọ́sà",
    ig: "Yabasi",
    ar: "بصل",
  },
  {
    commodityName: "Orange",
    en: {
      IN: "Orange",
      NG: "Orange",
      global: "Orange",
    },
    hi: "संतरा",
    or: "କମଳା",
    gu: "સંતરા",
    pt: "Laranja",
    fr: "Orange",
    ha: "Lemo",
    yo: "Ọsàn",
    ig: "Oroma",
    ar: "البرتقال",
  },
  {
    commodityName: "Papaya",
    en: {
      IN: "Papaya",
      NG: "Pawpaw",
      global: "Papaya",
    },
    hi: "पपीता",
    or: "ଅମୃତଭଣ୍ଡା",
    gu: "પપૈયું",
    pt: "Mamão",
    fr: "Papaye",
    ha: "Gwanda",
    yo: "Ìbẹ́pẹ",
    ig: "Pawpaw",
    ar: "البابايا",
  },
  {
    commodityName: "Peach",
    en: {
      IN: "Peach",
      NG: "Peach",
      global: "Peach",
    },
    hi: "आड़ू",
    or: "ପିଚ୍",
    gu: "પીચ",
    pt: "Pêssego",
    fr: "Pêche",
    ha: "Pich",
    yo: "Pisi",
    ig: "Pichi",
    ar: "خَوخ",
  },
  {
    commodityName: "Pear",
    en: {
      IN: "Pear",
      NG: "Pear",
      global: "Pear",
    },
    hi: "नाशपाती",
    or: "ନାଶପତି",
    gu: "નાશપતી",
    pt: "Pera",
    fr: "Poire",
    ha: "Piya",
    yo: "Piya",
    ig: "Paya",
    ar: "كُمَّثرَى",
  },
  {
    commodityName: "Peas",
    en: {
      IN: "Green Peas",
      NG: "Garden Peas",
      global: "Peas",
    },
    hi: "मटर",
    or: "ମଟର",
    gu: "વટાણા",
    pt: "Ervilhas",
    fr: "Petits pois",
    ha: "Wake",
    yo: "Ẹrẹpẹ",
    ig: "Pisi",
    ar: "البازلاء",
  },
  {
    commodityName: "Pineapple",
    en: {
      IN: "Pineapple",
      NG: "Pineapple",
      global: "Pineapple",
    },
    hi: "अनानास",
    or: "ସପୁରି",
    gu: "અનેનાસ / પાઈનેપલ",
    pt: "Abacaxi",
    fr: "Ananas",
    ha: "Abarba",
    yo: "Ọpẹ oyinbo",
    ig: "Ọpịpịa",
    ar: "أناناس",
  },
  {
    commodityName: "Plantain",
    en: {
      IN: "Raw Banana",
      NG: "Unripe Plantain",
      global: "Plantain",
    },
    hi: "कच्चा केला",
    or: "କଞ୍ଚା କଦଳୀ",
    gu: "કાચા કેલા (કાચું કેલું)",
    pt: "Banana-da-terra",
    fr: "Banane plantain",
    ha: "Ayaba",
    yo: "Ọgẹdẹ agbagba",
    ig: "Jị ọcha",
    ar: "موز الجنة",
  },
  {
    commodityName: "Pointed Gourd",
    en: {
      IN: "Parval",
      NG: "Snake Gourd",
      global: "Pointed Gourd",
    },
    hi: "परवल",
    or: "ପୋଟଳ",
    gu: "પરવર",
    pt: "Cabaça pontiaguda",
    fr: "Gourde pointue",
    ha: "Kabewa mai tsini",
    yo: "Ẹgúsí olójú píńpín",
    ig: "Ụgbọgụrụ imi",
    ar: "قرع مدبب",
  },
  {
    commodityName: "Pomegranate",
    en: {
      IN: "Pomegranate",
      NG: "Pomegranate",
      global: "Pomegranate",
    },
    hi: "अनार",
    or: "ଡାଳିମ୍ବ ",
    gu: "દાડમ",
    pt: "Romã",
    fr: "Grenade",
    ha: "Rumman",
    yo: "Pọmugiranetì",
    ig: "Pọmugiranetì",
    ar: "رمان",
  },
  {
    commodityName: "Pumpkin",
    en: {
      IN: "Kaddu",
      NG: "Pumpkin",
      global: "Pumpkin",
    },
    hi: "कद्दू",
    or: "କଖାରୁ",
    gu: "કોળું",
    pt: "Abóbora",
    fr: "Citrouille",
    ha: "Kabewa",
    yo: "Ẹlẹ́gẹ́dẹ́",
    ig: "Ugboguru",
    ar: "اليقطين",
  },
  {
    commodityName: "Radish",
    en: {
      IN: "Mooli",
      NG: "Radish",
      global: "Radish",
    },
    hi: "मूली",
    or: "ମୂଳI",
    gu: "મૂળો",
    pt: "Rabanete",
    fr: "Radis",
    ha: "Radish",
    yo: "Rẹ́díshì",
    ig: "Radishi",
    ar: "الفجل",
  },
  {
    commodityName: "Ridge Gourd",
    en: {
      IN: "Turai",
      NG: "Ridge Gourd",
      global: "Ridge Gourd",
    },
    hi: "तोरई",
    or: "ଯହିଁ",
    gu: "તુરિયા",
    pt: "Cabaça Ridge",
    fr: "Gourde de crête",
    ha: "Kabewa mai zango",
    yo: "Ẹgúsí onígbàrí",
    ig: "Ụgbọgụrụ akpụkpọ",
    ar: "القرع التلالي",
  },
  {
    commodityName: "Spinach",
    en: {
      IN: "Palak",
      NG: "Spinach",
      global: "Spinach",
    },
    hi: "पालक",
    or: "ପାଳଙ୍ଗ",
    gu: "પાલક",
    pt: "Espinafre",
    fr: "Épinard",
    ha: "Alayyaho",
    yo: "Ẹfọ tete",
    ig: "Spinachi",
    ar: "سبانخ",
  },
  {
    commodityName: "Spring onion",
    en: {
      IN: "Hara Pyaaz",
      NG: "Spring onion",
      global: "Spring onion",
    },
    hi: "हरी प्याज",
    or: "ଧଳା ପିଆଜ",
    gu: "લીલા કાંદા / સ્પ્રીંગ-ડુંગળી",
    pt: "Cebolinha",
    fr: "Oignon de printemps",
    ha: "Albasa mai kore",
    yo: "Àlùbọ́sà tútù",
    ig: "Alịbọsa ndu",
    ar: "البصل الأخضر",
  },
  {
    commodityName: "Strawberry",
    en: {
      IN: "Strawberry",
      NG: "Strawberry",
      global: "Strawberry",
    },
    hi: "स्ट्रॉबेरी",
    or: "ଷ୍ଟ୍ରଵବେରି",
    gu: "સ્ટ્રોબેરી",
    pt: "Morango",
    fr: "Fraise",
    ha: "Strawberry",
    yo: "Strawbérì",
    ig: "Strawberi",
    ar: "الفراولة",
  },
  {
    commodityName: "Raspberry",
    en: {
      IN: "Raspberry",
      NG: "Raspberry",
      global: "Raspberry",
    },
    hi: "रासबैरी",
    or: "ରସ୍ପବେରି",
    gu: "રાસ્પબેરી (રસભેરી)",
    pt: "Framboesa",
    fr: "Framboise",
    ha: "Raspberry",
    yo: "Raspbérì",
    ig: "Rasberi",
    ar: "توت العُليق",
  },
  {
    commodityName: "Sweet Lime",
    en: {
      IN: "Mosambi",
      NG: "Sweet Lime",
      global: "Sweet Lime",
    },
    hi: "मौसम्बी",
    or: "ମୌସମ୍ବି",
    gu: "મોસંબી",
    pt: "Limão doce",
    fr: "Citron doux",
    ha: "Lemun zaki",
    yo: "Ọsàn dídùn",
    ig: "Oroma ụtọ",
    ar: "ليمون حلو",
  },
  {
    commodityName: "Sweet Potato",
    en: {
      IN: "Shakarkand",
      NG: "Sweet Potato",
      global: "Sweet Potato",
    },
    hi: "शकरकंद",
    or: "ମିଠା ଆଳୁ",
    gu: "શક્કરિયા",
    pt: "Batata doce",
    fr: "Patate douce",
    ha: "Dankali mai yatsu",
    yo: "Ọ̀dúkún",
    ig: "Ji akwụkwọ",
    ar: "البطاطا الحلوة",
  },
  {
    commodityName: "Taro root",
    en: {
      IN: "Arbi",
      NG: "Cocoyam",
      global: "Taro root",
    },
    hi: "अरबी",
    or: "ସାରୁ",
    gu: "અરવી",
    pt: "Raiz de Taro",
    fr: "Racine de taro",
    ha: "Gwaza",
    yo: "Koko",
    ig: "Ede",
    ar: "جذر القلقاس",
  },
  {
    commodityName: "Tomato",
    en: {
      IN: "Tamatar",
      NG: "Tomato",
      global: "Tomato",
    },
    hi: "टमाटर",
    or: "ଟମାଟର",
    gu: "ટમેટું",
    pt: "Tomate",
    fr: "Tomate",
    ha: "Tumatur",
    yo: "Tòmátò",
    ig: "Tomato",
    ar: "طماطم",
  },
  {
    commodityName: "Water Melon",
    en: {
      IN: "Tarbooj",
      NG: "Water Melon",
      global: "Water Melon",
    },
    hi: "तरबूज",
    or: "ତରବୁଜ",
    gu: "તરબૂચ / વોટર મેલોન",
    pt: "Melancia",
    fr: "Pastèque",
    ha: "Kankana",
    yo: "Ẹgúsí bàrà",
    ig: "Watermelọn",
    ar: "بطيخ",
  },
  {
    commodityName: "Others",
    en: {
      IN: "Others",
      NG: "Others",
      global: "Others",
    },
    hi: "अन्य",
    or: "ଅନ୍ୟାନ୍ୟ",
    gu: "અન્ય",
    pt: "Outros",
    fr: "Autres",
    ha: "Wasu",
    yo: "Àwọn mìíràn",
    ig: "Ndị ọzọ",
    ar: "آحرون",
  },
  {
    commodityName: "Waterleaf",
    en: {
      IN: "Waterleaf",
      NG: "Waterleaf",
      global: "Waterleaf",
    },
    hi: "पानी का पत्ता",
    or: "ପାଣିପତ୍ର",
    gu: "પાણી નું પાંદડું",
    pt: "Folha d'água",
    fr: "Feuille d'eau",
    ha: "Ganyen ruwa",
    yo: "Gbure",
    ig: "Mgbolodi",
    ar: "ورقة الماء",
  },
  {
    commodityName: "Scent leaf",
    en: {
      IN: "Basil",
      NG: "Scent leaf",
      global: "African basil",
    },
    hi: "तुलसी",
    or: "ତୁଳସୀ",
    gu: "તુલસી",
    pt: "Manjericão africano",
    fr: "Basilic africain",
    ha: "Ganyen kamshi",
    yo: "Efirin",
    ig: "Nchanwu",
    ar: "الريحان الأفريقي",
  },
  {
    commodityName: "Roselle",
    en: {
      IN: "Roselle hibiscus",
      NG: "Zobo leaves",
      global: "Roselle",
    },
    hi: "गुड़हल",
    or: "କୋକିଆ",
    gu: "જાસૂદ",
    pt: "Rosela",
    fr: "Oseille de Guinée",
    ha: "Yakuwa",
    yo: "Isapa",
    ig: "Mkpiri",
    ar: "الكركديه",
  },
  {
    commodityName: "Oha/Ora Leaf",
    en: {
      IN: "Oha leaf",
      NG: "Ora/Oha leaf",
      global: "African oregano",
    },
    hi: "ओहा पत्ता",
    or: "ଓରା ପତ୍ର",
    gu: "ઓહા પાન",
    pt: "Orégano africano",
    fr: "Origan africain",
    ha: "Ganyen Oha",
    yo: "Ewe Oha",
    ig: "Oha",
    ar: "الأوريغانو الأفريقي",
  },
  {
    commodityName: "Jute leaves",
    en: {
      IN: "Jute leaves",
      NG: "Ewedu leaves",
      global: "Jute mallow",
    },
    hi: "पाट का साग",
    or: "ନଳିତା ପତ୍ର",
    gu: "સણનાં પાન",
    pt: "Folhas de caruru",
    fr: "Feuilles de corète",
    ha: "Ganyen Lalo",
    yo: "Ewedu",
    ig: "Ahihara",
    ar: "الملوخية",
  },
  {
    commodityName: "Fluted pumpkin (leaves)",
    en: {
      IN: "Fluted pumpkin leaves",
      NG: "Ugu leaves",
      global: "Fluted pumpkin leaves",
    },
    hi: "कद्दू के पत्ते",
    or: "କୁମ୍ଭଡା ପତ୍ର",
    gu: "કોળાનાં પાન",
    pt: "Folhas de abóbora nigeriana",
    fr: "Feuilles de courge cannelée",
    ha: "Ganyen Ugu",
    yo: "Ewe Ugwu",
    ig: "Ugu",
    ar: "أوراق اليقطين المضلع",
  },
  {
    commodityName: "Bitter Leaf",
    en: {
      IN: "Bitter leaf",
      NG: "Bitter leaf",
      global: "Vernonia",
    },
    hi: "करेला पत्ता",
    or: "ଚିରତା ପତ୍ର",
    gu: "કડવા પાન",
    pt: "Vernônia",
    fr: "Vernonie",
    ha: "Shuwaka",
    yo: "Ewuro",
    ig: "Onugbu",
    ar: "فيرنونيا",
  },
  {
    commodityName: "Lemon basil",
    en: {
      IN: "Lemon basil",
      NG: "Nchanwu",
      global: "Lemon basil",
    },
    hi: "निम्बू तुलसी",
    or: "ଲେମ୍ବୁ ତୁଳସୀ",
    gu: "લીંબુ તુલસી",
    pt: "Manjericão-limão",
    fr: "Basilic citron",
    ha: "Daddoya",
    yo: "Efinrin",
    ig: "Nchuanwu",
    ar: "الريحان الليموني",
  },
  {
    commodityName: "Avocado",
    en: {
      IN: "Butter fruit",
      NG: "Avocado pear",
      global: "Avocado",
    },
    hi: "मक्खन फल",
    or: "ମାଖନ ଫଳ",
    gu: "બટર ફ્રુટ",
    pt: "Abacate",
    fr: "Avocat",
    ha: "Avokado",
    yo: "Pia",
    ig: "Ube bekee",
    ar: "الأفوكادو",
  },
  {
    commodityName: "African star apple",
    en: {
      IN: "African star apple",
      NG: "Agbalumo",
      global: "African star apple",
    },
    hi: "अफ्रीकी तारा सेब",
    or: "ଆଫ୍ରିକୀୟ ତାରକା ସେବ",
    gu: "આફ્રિકન સ્ટાર એપલ",
    pt: "Maçã estrela africana",
    fr: "Pomme étoile africaine",
    ha: "Agbaluba",
    yo: "Agbalumo",
    ig: "Udara",
    ar: "تفاح النجمة الأفريقي",
  },
];
export type CropListDatum = (typeof CROP_LIST)[number];

export const KNOWLEDGE_HUB_LIST = [
  {
    commodityName: "Capsicum (Bell Pepper)",
    optimalTemperature: "7-10 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/banana.png",
  },
  {
    commodityName: "Apple",
    optimalTemperature: "-1.1-0 °C",
    storageLife: "3-6 months",
    image: "crop_images/apple.png",
  },
  {
    commodityName: "Banana",
    optimalTemperature: "13-15 °C",
    storageLife: "1-4 weeks",
    image: "crop_images/banana.png",
  },
  {
    commodityName: "Green beans",
    optimalTemperature: "4-7 °C",
    storageLife: "7-10 days",
    image: "crop_images/beans.png",
  },
  {
    commodityName: "Beetroot",
    optimalTemperature: "0 °C",
    storageLife: "4 months",
    image: "crop_images/beetroot.png",
  },
  {
    commodityName: "Bitter Gourd",
    optimalTemperature: "10-12 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/bitterGourd.png",
  },
  {
    commodityName: "Bottle Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/bottleGourd.png",
  },
  {
    commodityName: "Broccoli",
    optimalTemperature: "0 °C",
    storageLife: "10-14 days",
    image: "crop_images/broccoli1.png",
  },
  {
    commodityName: "Cabbage",
    optimalTemperature: "0°C",
    storageLife: "3-6 weeks",
    image: "crop_images/cabbage.png",
  },
  {
    commodityName: "Carrot",
    optimalTemperature: "0 °C",
    storageLife: "3-6 months",
    image: "crop_images/carrot.png",
  },
  {
    commodityName: "Tapioca (Cassava)",
    optimalTemperature: "0-5 °C",
    storageLife: "1-2 months",
    image: "crop_images/cassava.png",
  },
  {
    commodityName: "Cauliflower",
    optimalTemperature: "0 °C",
    storageLife: "3-4 weeks",
    image: "crop_images/cauliflower_dVI5dHi.jpg",
  },
  {
    commodityName: "Bathua (Chenopodium)",
    optimalTemperature: "0-5 °C",
    storageLife: "1-2 weeks",
    image: "crop_images/Screenshot_2022-07-27_at_17.38.06_wEQtrsl.png",
  },
  {
    commodityName: "Colacasia",
    optimalTemperature: "7-10 °C",
    storageLife: "4 months",
    image: "crop_images/cocoyam.png",
  },
  {
    commodityName: "Coriander",
    optimalTemperature: "0-1 °C",
    storageLife: "2 weeks",
    image: "crop_images/coriander.png",
  },
  {
    commodityName: "Cucumber",
    optimalTemperature: "10-12 °C",
    storageLife: "7 days",
    image: "crop_images/cucumber.png",
  },
  {
    commodityName: "Drum stick",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/drumStick.png",
  },
  {
    commodityName: "Brinjal (Aubergine)",
    optimalTemperature: "10-12 °C",
    storageLife: "1-2 weeks",
    image: "crop_images/eggplant.png",
  },
  {
    commodityName: "Flat Beans",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/flatBeans.png",
  },
  {
    commodityName: "Garlic",
    optimalTemperature: "-1-1 °C",
    storageLife: "6-7 months",
    image: "crop_images/garlic.png",
  },
  {
    commodityName: "Ginger",
    optimalTemperature: "13 °C",
    storageLife: "6 months",
    image: "crop_images/ginger.png",
  },
  {
    commodityName: "Grapes",
    optimalTemperature: "-0.5-0 °C",
    storageLife: "1-6 months",
    image: "crop_images/grapes.png",
  },
  {
    commodityName: "Green Chilli",
    optimalTemperature: "5-10 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/greenChilly_T8YSJBd.png",
  },
  {
    commodityName: "Green Gram",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/greenGram.png",
  },
  {
    commodityName: "Guava",
    optimalTemperature: "5-10 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/guava_NEW.jpg",
  },
  {
    commodityName: "Irish Potato",
    optimalTemperature: "4-8 °C",
    storageLife: "5-10 months",
    image: "crop_images/potato.png",
  },
  {
    commodityName: "Ivy Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/ivy-Gourd.png",
  },
  {
    commodityName: "Jackfruit",
    optimalTemperature: "13 °C",
    storageLife: "2-4 weeks",
    image: "crop_images/jackfruit_kBpd54C_vSzqJWD.jpg",
  },
  {
    commodityName: "Lemon",
    optimalTemperature: "10-13 °C",
    storageLife: "1-6 months",
    image: "crop_images/lemon.png",
  },
  {
    commodityName: "Lettuce",
    optimalTemperature: "0 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/lettuce.png",
  },
  {
    commodityName: "Litchi",
    optimalTemperature: "1-2 °C",
    storageLife: "3-5 weeks",
    image: "crop_images/litchi.png",
  },
  {
    commodityName: "Mango",
    optimalTemperature: "13 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/mango.png",
  },
  {
    commodityName: "Musk Melon",
    optimalTemperature: "5-10 °C",
    storageLife: "3-4 weeks",
    image: "crop_images/melon.png",
  },
  {
    commodityName: "Mint leaves",
    optimalTemperature: "0 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/mint.png",
  },
  {
    commodityName: "Methi",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/moringa-leaves.png",
  },
  {
    commodityName: "Mushroom",
    optimalTemperature: "0 °C",
    storageLife: "7-14 days",
    image: "crop_images/mushroom.png",
  },
  {
    commodityName: "Ladyfinger",
    optimalTemperature: "7-10 °C",
    storageLife: "7-10 days",
    image: "crop_images/okra.png",
  },
  {
    commodityName: "Onion",
    optimalTemperature: "0 °C",
    storageLife: "1-8 months",
    image: "crop_images/onion.png",
  },
  {
    commodityName: "Orange",
    optimalTemperature: "3-9 °C",
    storageLife: "3-8 weeks",
    image: "crop_images/orange.png",
  },
  {
    commodityName: "Papaya",
    optimalTemperature: "7-13 °C",
    storageLife: "1-3 weeks",
    image: "crop_images/papaya.png",
  },
  {
    commodityName: "Peach",
    optimalTemperature: "-0.5-0 °C",
    storageLife: "2-4 weeks",
    image: "crop_images/Screenshot_2022-07-27_at_17.38.48_25wWCxW.png",
  },
  {
    commodityName: "Pear",
    optimalTemperature: "-1.5 to -0.5 °C",
    storageLife: "2-7 months",
    image: "crop_images/pear.png",
  },
  {
    commodityName: "Peas",
    optimalTemperature: "0 °C",
    storageLife: "1-2 weeks",
    image: "crop_images/peas.png",
  },
  {
    commodityName: "Pineapple",
    optimalTemperature: "7-13 °C",
    storageLife: "2-4 weeks",
    image: "crop_images/pineapple.png",
  },
  {
    commodityName: "Plantain",
    optimalTemperature: "13-15 °C",
    storageLife: "1-5 weeks",
    image: "crop_images/plantains.png",
  },
  {
    commodityName: "Pointed Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/Screenshot_2022-07-27_at_17.40.24_nI20Ox2.png",
  },
  {
    commodityName: "Pomegranate",
    optimalTemperature: "5-7.2 °C",
    storageLife: "2-3 months",
    image: "crop_images/pomegranate.png",
  },
  {
    commodityName: "Pumpkin",
    optimalTemperature: "12-15 °C",
    storageLife: "2-3 months",
    image: "crop_images/pumpkin_Z60xebw.jpg",
  },
  {
    commodityName: "Radish",
    optimalTemperature: "0 °C",
    storageLife: "1-2 months",
    image: "crop_images/radish.png",
  },
  {
    commodityName: "Ridge Gourd",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/ridgeGourd.png",
  },
  {
    commodityName: "Spinach",
    optimalTemperature: "0 °C",
    storageLife: "10-14 days",
    image: "crop_images/spinach.png",
  },
  {
    commodityName: "Spring onion",
    optimalTemperature: "0 °C",
    storageLife: "3 weeks",
    image: "crop_images/springOnion.png",
  },
  {
    commodityName: "Strawberry",
    optimalTemperature: "0 °C",
    storageLife: "7-10 days",
    image: "crop_images/strawberry.png",
  },
  {
    commodityName: "Sweet Lime",
    optimalTemperature: "10-13 °C",
    storageLife: "1-6 months",
    image: "crop_images/SweetLime.png",
  },
  {
    commodityName: "Taro root",
    optimalTemperature: "7-10 °C",
    storageLife: "4 months",
    image: "crop_images/taro-root.png",
  },
  {
    commodityName: "Tomato",
    optimalTemperature: "8-13 °C",
    storageLife: "1-3 weeks",
    image: "crop_images/tomato.png",
  },
  {
    commodityName: "Water Melon",
    optimalTemperature: "10-15 °C",
    storageLife: "2-3 weeks",
    image: "crop_images/waterMelon2.png",
  },
  {
    commodityName: "Scent leaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/Scent_leaves.jpg",
  },
  {
    commodityName: "Roselle",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/Roselle.png",
  },
  {
    commodityName: "Oha/Ora Leaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/OhaLeaves.jpg",
  },
  {
    commodityName: "Jute leaves",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/Jute_GTIG44R.png",
  },
  {
    commodityName: "Fluted pumpkin (leaves)",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/Fluted_pumpkin_leaves.png",
  },
  {
    commodityName: "Bitter Leaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/BitterLeaf.png",
  },
  {
    commodityName: "Avocado",
    optimalTemperature: "3-7°C",
    storageLife: "2-4 weeks",
    image: "crop_images/Avocado.png",
  },
  {
    commodityName: "African star apple",
    optimalTemperature: "15°C",
    storageLife: "15 days",
    image: "crop_images/AfricanStarApple.png",
  },
  {
    commodityName: "Lemon basil",
    optimalTemperature: "10 °C",
    storageLife: "7",
    image: "crop_images/1.png",
  },
  {
    commodityName: "Waterleaf",
    optimalTemperature: "N/A",
    storageLife: "N/A",
    image: "crop_images/waterleaf_PUYc7v0.png",
  },
  {
    commodityName: "Raspberry",
    optimalTemperature: "0°C",
    storageLife: "2-5 days",
    image: "crop_images/raspberry.png",
  },
];
export type KnowledgeHubListDatum = (typeof KNOWLEDGE_HUB_LIST)[number];
