import { createNanoEvents, type Unsubscribe } from 'nanoevents';
import { useEffect, useLayoutEffect, useRef } from 'react';

export const APP_EVENTS = {
  DISPATCH_PAYMENT_PENDING_BOTTOM_SHEET: 'DISPATCH_PAYMENT_PENDING_BOTTOM_SHEET',
  DISPATCH_CROPS_BOTTOM_SHEET: 'DISPATCH_CROPS_BOTTOM_SHEET',
  DISPATCH_FEE_BREAKDOWN_BOTTOM_SHEET: 'DISPATCH_FEE_BREAKDOWN_BOTTOM_SHEET',
  DISPATCH_CU_PROMPT: 'DISPATCH_CU_PROMPT',
  DISPATCH_CU_FORM_MODAL: 'DISPATCH_CU_FORM_MODAL',
  DISPATCH_SENSOR_PROMPT: 'DISPATCH_SENSOR_PROMPT',
  DISPATCH_SENSOR_MODAL: 'DISPATCH_SENSOR_MODAL',
  DISPATCH_SENSOR_DATUMS: 'DISPATCH_SENSOR_DATUMS',
  DISPATCH_SENSOR_LIST_MODAL: 'DISPATCH_SENSOR_LIST_MODAL',
  DISPATCH_MAPS_TAB_MODAL: 'DISPATCH_MAPS_TAB_MODAL',
  DISPATCH_NOTIFICATION_OPEN_SURVEY: 'DISPATCH_NOTIFICATION_OPEN_SURVEY',
  DISPATCH_NOTIFICATION_OPEN_COMMODITY_MODAL: 'DISPATCH_NOTIFICATION_OPEN_COMMODITY_MODAL',
  DISPATCH_NOTIFICATION_ORDER_REQUIRES_MOVEMENT_MODAL:
    'DISPATCH_NOTIFICATION_ORDER_REQUIRES_MOVEMENT_MODAL',
  DISPATCH_CHECK_IN_TEMPERATURE_ALERT: 'DISPATCH_CHECK_IN_TEMPERATURE_ALERT',
  DISPATCH_MARKETPLACE_COMPANY_MODAL: 'DISPATCH_MARKETPLACE_COMPANY_MODAL',
  DISPATCH_MARKETPLACE_ADD_TO_CART_MODAL: 'DISPATCH_MARKETPLACE_ADD_TO_CART_MODAL',
  DISPATCH_MARKETPLACE_FILTERS_FORM_SUBMISSION: 'DISPATCH_MARKETPLACE_FILTERS_FORM_SUBMISSION',
  DISPATCH_MARKETPLACE_FILTERS_FORM_RESET: 'DISPATCH_MARKETPLACE_FILTERS_FORM_RESET',
  DISPATCH_SHOPPING_CART_DELIVERY_INFORMATION: 'DISPATCH_SHOPPING_CART_DELIVERY_INFORMATION',
  DISPATCH_ADD_COUPON_IN_CART_MODAL: 'DISPATCH_ADD_COUPON_IN_CART_MODAL',
  DISPATCH_LIST_COUPONS_IN_CART_MODAL: 'DISPATCH_LIST_COUPONS_IN_CART_MODAL',
  DISPATCH_DELIVERY_CONTACT_BOTTOM_SHEET: 'DISPATCH_DELIVERY_CONTACT_BOTTOM_SHEET',
  DISPATCH_RELOAD_DELIVERY_CONTACTS: 'DISPATCH_RELOAD_DELIVERY_CONTACTS',
  DISPATCH_CLOSE_MARKETPLACE_TOOLTIPS: 'DISPATCH_CLOSE_MARKETPLACE_TOOLTIPS',
  DISPATCH_COMPANY_BANK_ACCOUNT_MODAL: 'DISPATCH_COMPANY_BANK_ACCOUNT_MODAL',
  DISPATCH_PICK_UP_METHODS_SELECTION: 'DISPATCH_PICK_UP_METHODS_SELECTION',
  DISPATCH_CLOSE_OPERATOR_ACTIONS: 'DISPATCH_CLOSE_OPERATOR_ACTIONS',
  DISPATCH_OPEN_OPERATOR_ACTIONS: 'DISPATCH_OPEN_OPERATOR_ACTIONS',
  DISPATCH_INVALIDATE_MARKETPLACE_COORDINATES: 'DISPATCH_INVALIDATE_MARKETPLACE_COORDINATES',
  DISPATCH_INVALIDATE_MARKETPLACE_LISTING: 'DISPATCH_INVALIDATE_MARKETPLACE_LISTING',
} as const;

export const emitter = createNanoEvents();

export function useAppEventListener<T extends Array<unknown>>(
  eventName: keyof typeof APP_EVENTS,
  cb: (...args: T) => void
) {
  const savedCallback = useRef(cb);

  useLayoutEffect(() => {
    savedCallback.current = cb;
  }, [cb]);

  useEffect(() => {
    let unsub: Unsubscribe | undefined = undefined;
    if (typeof savedCallback.current === 'function') {
      unsub = emitter.on(eventName, savedCallback.current);
    }
    return () => {
      unsub?.();
    };
  }, []);
}
